from SourcePlugins.Seatgeek.BusRule_SeatgeekPlans import *
from SourcePlugins.Seatgeek.BusRule_SeatgeekClients import *
from SourcePlugins.Seatgeek.BusRule_SeatgeekPayments import *
from SourcePlugins.Seatgeek.BusRule_SeatgeekInstallments import *
from SourcePlugins.Seatgeek.BusRule_SeatgeekPricing import *
from SourcePlugins.Seatgeek.BusRule_SeatgeekProducts import *
from SourcePlugins.Seatgeek.BusRule_SeatgeekManifests import *
from SourcePlugins.Seatgeek.BusRule_SeatgeekSales import *

from Library.FunctionFiles.Functions import *
from Library.Class.Document import *

deleteraw_order = 7
create_archive_tables = ["seatgeekclients", "seatgeekpayments", "seatgeekinstallments", "seatgeekpricing", "seatgeekproducts", "seatgeekmanifests", "seatgeeksales"]

def fn_busrules_append(worksheet:object, bus_rule_obj:object, db_folder:str, runlog:object):
    runlog.log("Running Seatgeek specific busrules append function")

    # get table name
    table_name = worksheet.table_name().upper().replace("_","")

    # get columns
    col_list = worksheet.columns()

    # get primary keys
    pk = worksheet.primary_keys()

    # get phone columns
    phone_col_list = worksheet.phone_columns()

    if table_name == "SEATGEEKPLANS":
        seatgeekplans_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    if table_name == "SEATGEEKCLIENTS":
        seatgeekclients_busrules(col_list=col_list, pk=pk, phone_col_list=phone_col_list, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    if table_name == "SEATGEEKPAYMENTS":
        seatgeekpayments_busrules(col_list=col_list, pk=pk, phone_col_list=phone_col_list, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    if table_name == "SEATGEEKINSTALLMENTS":
        seatgeekinstallments_busrules(col_list=col_list, pk=pk, phone_col_list=phone_col_list, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    if table_name == "SEATGEEKPRICING":
        seatgeekpricing_busrules(col_list=col_list, pk=pk, phone_col_list=phone_col_list, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    if table_name == "SEATGEEKPRODUCTS":
        seatgeekproducts_busrules(col_list=col_list, pk=pk, phone_col_list=phone_col_list, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    if table_name == "SEATGEEKMANIFESTS":
        seatgeekmanifests_busrules(col_list=col_list, pk=pk, phone_col_list=phone_col_list, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    if table_name == "SEATGEEKSALES":
        seatgeeksales_busrules(col_list=col_list, pk=pk, phone_col_list=phone_col_list, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    runlog.log("")
    return

def fn_create_import_DDL_custom(table_name:str, col_list:list, version:str, db_folder:str, runlog:object, repo_root_folder:str, client:str, source_name:str, data_resources:list):
    # create normal import table
    create_import_DDL(table_name=table_name, col_list=col_list, version=version, db_folder=db_folder, runlog=runlog, repo_root_folder=repo_root_folder, client=client, source_name=source_name)
    # append data resources
    data_resources.append(["import", table_name.lower()])

    # get table name
    table_name = table_name.upper().replace("_","")

    # create cursor tracking table
    if table_name != "SEATGEEKEVENTS" and table_name != "SEATGEEKPLANS":
        runlog.log(f"Creating Cursor Tracking import table for {table_name}")
        table_name = f"{table_name}_CURSOR_TRACKING"
        CursorDDL = Document()

        CursorDDL.newline(f"/*{table_name} (Import) grantObjectName={table_name} version=1 generated by config generator */")
        CursorDDL.newline(f"CREATE TABLE IF NOT EXISTS IMPORT.{table_name}")
        CursorDDL.newline("(")
        CursorDDL.newline("\tCURSOR_ID\tNUMBER(38,0)\tNOT NULL\tAUTOINCREMENT START 1 INCREMENT 1,")
        CursorDDL.newline("\tCURSOR\tVARCHAR(16777216),")
        CursorDDL.newline("\tHAS_MORE\tBOOLEAN,")
        CursorDDL.newline("\tCURSOR_UPDATED\tBOOLEAN\tDEFAULT TRUE NOT NULL,")
        CursorDDL.newline("\tCURSOR_FAILED\tBOOLEAN\tDEFAULT FALSE NOT NULL,")
        CursorDDL.newline("\tFOLDER_TIMESTAMP\tVARCHAR(16777216),")
        CursorDDL.newline("\tDWINSERTDATE\tTIMESTAMP_LTZ\tNOT NULL\tDEFAULT CURRENT_TIMESTAMP(),")
        CursorDDL.newline("\tDWUPDATEDATE\tTIMESTAMP_LTZ\tNOT NULL\tDEFAULT CURRENT_TIMESTAMP()")
        CursorDDL.newline("\tACQUIRE_COMPLETE\tBOOLEAN\tNOT NULL\tDEFAULT FALSE")
        CursorDDL.newline("\tINGEST_COMPLETE\tBOOLEAN\tNOT NULL\tDEFAULT FALSE")
        CursorDDL.newline("\tIS_LATEST_ACQUIRE\tBOOLEAN\tNOT NULL\tDEFAULT FALSE")

        CursorDDL.newline(");")

        # define output folder and filename
        filename = f"{table_name.lower()}.sql"
        output_folder = f"{db_folder}data_repo{os.sep}import{os.sep}"
        filewrite(folder=output_folder, filename=filename, content=CursorDDL.out())
        print_section_detail(msg=f"IMPORT CURSOR TRACKING DDL - {filename}\nCreated in: {output_folder}", runlog=runlog)

        # write output repo files if repo_root_folder is not empty
        if repo_root_folder != "":
            datarepo_folder = f"{repo_root_folder}data{os.sep}warehouse{os.sep}{source_name.lower()}{os.sep}import{os.sep}{client.upper()}{os.sep}"
            filewrite(folder=datarepo_folder, filename=filename, content=CursorDDL.out())
            print_section_detail(msg=f"IMPORT CURSOR TRACKING DDL - {filename}\nCreated in: {datarepo_folder}", runlog=runlog)

        # append data resources
        data_resources.append(["import", table_name.lower()])

    return

# create acquire file
def fn_create_acquire_file(file_match_list:list, table_name_list:list, db_folder:str, runlog:object, client:str, repo_root_folder:str, acquire_custom_info_list:list):
    print_section(msg="Working on Acquire File", runlog=runlog)

    acquire_file = {}

    endpoints = []

    for file in file_match_list:
        if "attendance" in file:
            endpoints.append("attendance")
        elif "clients" in file:
            endpoints.append("clients")
        elif "manifests" in file:
            endpoints.append("manifests")
        elif "payments" in file:
            endpoints.append("payments")
        elif "products" in file:
            endpoints.append("products")
        elif "sales" in file:
            endpoints.append("sales")
        elif "installments" in file:
            endpoints.append("installments")
        elif "pricing" in file:
            endpoints.append("pricing")

    acquire_file["endpoints"] = endpoints
    acquire_file["limit"] = 10000

    # filename
    filename = f"acquire.json"

    # output JSON
    writeJSON(filecontent=acquire_file, filename=filename, filetype="acquire", client=client, source_name="seatgeek", db_folder=db_folder, repo_root_folder=repo_root_folder, runlog=runlog)

    return

# sources append
def fn_sources_append(worksheet:object, db_folder:str, sources_obj:object, runlog:object, repo_root_folder:str, client:str, source_name:str):
    runlog.log("Running Seatgeek specific sources append function")

    # get table name
    table_name = worksheet.table_name()

    # add importsql steps if table is products
    if table_name == "SEATGEEKPRODUCTS":
        runlog.log("Add events truncate and flatten to products importsql")
        events_importsql_truncate = {}
        events_importsql_truncate["sortOrder"] = 3
        events_importsql_truncate["sqlFileName"] = "seatgeekevents-truncate.sql"
        events_importsql_truncate["saveResults"] = False

        events_importsql_flatten = {}
        events_importsql_flatten["sortOrder"] = 4
        events_importsql_flatten["sqlFileName"] = "seatgeekevents-flatten.sql"

        sources_obj.append("importSql", [events_importsql_truncate])
        sources_obj.append("importSql", [events_importsql_flatten])

        runlog.log("Add plans truncate and flatten to products importsql")
        plans_importsql_truncate = {}
        plans_importsql_truncate["sortOrder"] = 5
        plans_importsql_truncate["sqlFileName"] = "seatgeekplans-truncate.sql"
        plans_importsql_truncate["saveResults"] = False

        plans_importsql_flatten = {}
        plans_importsql_flatten["sortOrder"] = 6
        plans_importsql_flatten["sqlFileName"] = "seatgeekplans-flatten.sql"

        sources_obj.append("importSql", [plans_importsql_truncate])
        sources_obj.append("importSql", [plans_importsql_flatten])
    elif table_name == "SEATGEEKEVENTS" or table_name == "SEATGEEKPLANS":
        sources_obj.append("importSql","NOTRUNCATE")
        sources_obj.append("importSql", "NOFLATTEN")

    return