from Library.FunctionFiles.Functions import *
from Library.Class.Document import *
from SourcePlugins.Podium.Flatten_Podium import *

custom_filedate = "TO_CHAR(REGEXP_SUBSTR(METADATA$FILENAME, '[0-9]{14}', 1, 1))"

# Customize column list
def customize_col_list(table_name:str, col_list:list):
    if table_name.upper() == "PODIUMCONTACTS":
        col_list_custom = []
        for col in col_list:
            if col[1].upper() == "MIDDLE_NAME" or col[1].upper() == "LAST_NAME":
                continue
            elif col[1].upper() == "FIRST_NAME":
                col_list_custom.append(["name", "name", "VARCHAR(16777216)"])
            else:
                col_list_custom.append(col)
    else:
        col_list_custom = col_list

    return col_list_custom

# Build import DDL
def fn_create_import_DDL_custom(table_name:str, col_list:list, version:str, db_folder:str, runlog:object, repo_root_folder:str, client:str, source_name:str, data_resources:list):
    runlog.log("Running Podium specific import DDL function")

    # col_list_custom = customize_col_list(table_name, col_list)
    col_list_custom = col_list

    # create normal import table
    create_import_DDL(table_name=table_name, col_list=col_list_custom, version=version, db_folder=db_folder, runlog=runlog, repo_root_folder=repo_root_folder, client=client, source_name=source_name)
    # append data resources
    data_resources.append(["import", table_name.lower()])

    if ["stage", "podiumtracking"] not in data_resources:
        # add tracking table deployment
        data_resources.append(["stage", "podiumtracking"])
        data_resources.append(["stage", "sp_getlastsuccesfulcursor"])
        data_resources.append(["stage", "sp_inserttrackingrecord"])
        data_resources.append(["stage", "sp_updatesuccessflag"])

    return

def create_flatten_podiumcontacts(source_name:str, table_name:str, table_name_raw:str, col_list:list, version:str, db_folder:str, runlog:object, repo_root_folder:str, client:str):
    # initialize Flatten Document
    Flatten = Document()
    insertcolumns = []
    selectcolumns = []

    # create column list for insert and json sections
    for col in col_list:
        insertcolumns.append(f"\t{str(col[1]).upper()}")
        if str(col[1]).upper() == "FIRST_NAME":
            FIRST_NAME = "\tSPLIT_PART(IFNULL(TRIM(CAST(FULL_NAME AS STRING)), ''), ' ', 0) AS FIRST_NAME"
            selectcolumns.append(FIRST_NAME)
        elif str(col[1]).upper() == "MIDDLE_NAME":
            MIDDLE_NAME = ("\tCASE"
                           "\n\t\tWHEN FULL_NAME ILIKE '% % %'"
                           "\n\t\tTHEN SPLIT_PART(IFNULL(TRIM(CAST(FULL_NAME AS STRING)), ''), ' ', 2)"
                           "\n\t\tELSE ''"
                           "\n\tEND AS MIDDLE_NAME")
            selectcolumns.append(MIDDLE_NAME)
        elif str(col[1]).upper() == "LAST_NAME":
            LAST_NAME = ("\tCASE"
                         "\n\t\tWHEN FULL_NAME ILIKE '% % %'"
                         "\n\t\tTHEN SPLIT_PART(IFNULL(TRIM(CAST(FULL_NAME AS STRING)), ''), ' ', 3)"
                         "\n\t\tELSE"
                         "\n\t\tCASE"
                         "\n\t\t\tWHEN FULL_NAME ILIKE '% %'"
                         "\n\t\t\tTHEN SPLIT_PART(IFNULL(TRIM(CAST(FULL_NAME AS STRING)), ''), ' ', 2)"
                         "\n\t\tEND"
                         "\n\tEND AS LAST_NAME")
            selectcolumns.append(LAST_NAME)
        else:
            selectcolumns.append(f"\t{str(col[1]).upper()}")

    # initialize elements of insert statement
    Flatten.append(f"/*{table_name} Flatten Insert version={version} generated by config generator */")
    Flatten.newline(f"INSERT INTO import.{table_name.lower()}")
    Flatten.newline("(")
    Flatten.newline("\tFILEDATE,")
    Flatten.newline("\tFILENAME,")
    Flatten.newline("\tFILEROWNUMBER,")
    Flatten.newlinelist(insertcolumns)
    Flatten.newline(")")
    Flatten.newline(f"WITH FLATTENJSON AS")
    Flatten.newline("(")
    Flatten.newline(flattenjson_podiumcontacts(table_name, table_name_raw, col_list))
    Flatten.newline(")")
    Flatten.newline("SELECT")
    Flatten.newline("\tFILEDATE,")
    Flatten.newline("\tFILENAME,")
    Flatten.newline("\tFILEROWNUMBER,")
    Flatten.newlinelist(selectcolumns)
    Flatten.newline("FROM FLATTENJSON;")

    # define output folder and filename
    filename = f"{table_name.lower()}-flatten.sql"

    # define folder output path
    output_folder = f"{db_folder}config_repo{os.sep}sources{os.sep}"
    filewrite(folder=output_folder, filename=filename, content=Flatten.out())
    print_section_detail(msg=f"FLATTEN - {filename}\nCreated in: {output_folder}", runlog=runlog)

    # write output repo files if repo_root_folder is not empty
    if repo_root_folder != "":
        configrepo_folder = f"{repo_root_folder}kagr-configuration{os.sep}prefect{os.sep}{client.upper()}{os.sep}{source_name.lower()}{os.sep}sources{os.sep}"
        filewrite(folder=configrepo_folder, filename=filename, content=Flatten.out())
        print_section_detail(msg=f"FLATTEN - {filename}\nCreated in: {configrepo_folder}", runlog=runlog)

    return filename
# Create flatten
def fn_create_flatten_custom(source_name:str, table_name:str, table_name_raw:str, col_list:list, version:str, db_folder:str, runlog:object, repo_root_folder:str, client:str, worksheet: object):
    runlog.log("Running Podium specific flatten function")

    # col_list_custom = customize_col_list(table_name, col_list)
    col_list_custom = col_list

    if table_name.upper() == "PODIUMCONTACTS":
        flatten_filename = create_flatten_podiumcontacts(source_name=source_name, table_name=table_name.lower(), table_name_raw=table_name_raw, col_list=col_list_custom, version=version, db_folder=db_folder, runlog=runlog, repo_root_folder=repo_root_folder, client=client)
    else:
        flatten_filename = create_flatten(source_name=source_name, table_name=table_name.lower(), table_name_raw=table_name_raw, col_list=col_list_custom, version=version, db_folder=db_folder, runlog=runlog, repo_root_folder=repo_root_folder, client=client)

    return flatten_filename

# create feature file
def fn_create_feature_file_custom(source_name:str, table_name_list:list, db_folder:str, runlog:object, repo_root_folder:str, client:str):
    print_section(msg="Working on Podium custom Feature File", runlog=runlog)

    feature_file = {}
    feature_file_append = []

    # create sources key value dictionary per table
    sources_list = []
    transform_groups_sources0 = []
    transform_groups_sources1 = []
    for table in table_name_list:
        table_name = table[0].lower()
        has_bus_rule = table[1]
        sources_dict = {}
        sources_dict["name"] = table_name
        sources_dict["configurationFileName"] = f"{table_name}.json"
        sources_dict["hasBusinessRules"] = has_bus_rule
        if table_name == "podiumconversations" or table_name == "podiummessages":
            transform_groups_sources1.append(table_name)
        else:
            transform_groups_sources0.append(table_name)

        sources_list.append(sources_dict)

    feature_file["sources"] = sources_list
    feature_file["featureName"] = source_name.lower()

    # transform groups
    transformGroupsList = []
    transformGroupsDict0 = {}
    transformGroupsDict0["runOrder"] = 0
    transformGroupsDict0["sources"] = transform_groups_sources0
    transformGroupsList.append(transformGroupsDict0)

    transformGroupsDict1 = {}
    transformGroupsDict1["runOrder"] = 1
    transformGroupsDict1["sources"] = transform_groups_sources1
    transformGroupsList.append(transformGroupsDict1)

    feature_file["transformGroups"] = transformGroupsList

    # define output folder and filename
    # filename
    filename = f"{source_name.lower()}.json"

    # output JSON
    writeJSON(filecontent=feature_file, filename=filename, filetype="feature", client=client, source_name=source_name, db_folder=db_folder, repo_root_folder=repo_root_folder, runlog=runlog)

    return

# create unique sp
def fn_create_unique_sp_custom(table_name:str, pk_list:list, col_list:list, db_folder:str, runlog:object, std_ind:str, repo_root_folder:str, client:str, source_name:str, import_view_name:str="", create_keyhash:str="0"):
    if 'CONTACTS' not in table_name.upper():
        unique_sp_name = create_unique_sp(table_name=table_name, pk_list=pk_list, col_list=col_list, db_folder=db_folder, runlog=runlog, std_ind=std_ind, repo_root_folder=repo_root_folder, client=client, source_name=source_name, import_view_name=import_view_name)

    else:
        #--------------------------------------------------
        # helper functions
        # --------------------------------------------------
        def split_schema_table(table_name: str):
            # if table_name has schema, split it up
            if "." in table_name:
                table_name_list = table_name.split(".")
                table_schema = table_name_list[0].upper()
                tablename_noschema = table_name_list[1].upper()
            else:
                table_schema = "IMPORT"
                tablename_noschema = table_name.upper()

            return table_schema, tablename_noschema

        def remove_chars(input: str, char_to_remove: list):
            query_str = input
            for char in char_to_remove:
                query_str = f"REPLACE({query_str},'{char}','')"

            return query_str

        # --------------------------------------------------

        # map import table name to either table or view
        if len(import_view_name) > 0:
            table_schema, tablename_noschema = split_schema_table(import_view_name)
        else:
            table_schema, tablename_noschema = split_schema_table(table_name)

        import_table_name = tablename_noschema

        # if audience table, map to melissa tmp table
        if std_ind == "1":
            table_schema = "TMP"
            import_table_name = f"{import_table_name.upper()}melissa"

        # define SP name
        unique_sp_name = f"tmp.sp_createtable{table_name.lower()}unique()"

        # initialize unique query document
        uniquesp = Document()

        # write query
        uniquesp.append(f"/* sp_CreateTable{table_name.upper()}Unique (tmp) grantobjectname=tmp.sp_CreateTable{table_name.upper()}Unique version=1 */")
        uniquesp.newline("!set exit_on_error=true;")
        uniquesp.newline("!set variable_substitution=true;")
        uniquesp.newline("")
        uniquesp.newline(f"CREATE OR REPLACE PROCEDURE {unique_sp_name}")
        uniquesp.newline("\treturns varchar not null")
        uniquesp.newline("\tlanguage sql")
        uniquesp.newline("\texecute as caller")
        uniquesp.newline("AS")
        uniquesp.newline("$$")
        uniquesp.newline("\tBEGIN")
        uniquesp.newline(f"\t\tCREATE OR REPLACE TABLE TMP.{table_name.upper()}UNIQUE")
        uniquesp.newline("\t\tAS")
        uniquesp.newline("\t\tSELECT DISTINCT")
        uniquesp.newline("\t\t\tFILEDATE,")
        uniquesp.newline("\t\t\tFILENAME,")
        uniquesp.newline("\t\t\tFILEROWNUMBER,")

        if create_keyhash == "1":
            uniquesp.newline(f"\t\t\tKEYHASH,")

        for row in col_list:
            uniquesp.newline(f"\t\t\t{row[1]},")

        if std_ind == "1":
            uniquesp.newline("\t\t\tSTANDARDIZATIONROWID")
        else:
            # remove trailing comma
            uniquesp.trimend(1)

        uniquesp.newline("\t\tFROM")
        uniquesp.newline("\t\t(")

        uniquesp.newline("\t\t\tSELECT")
        uniquesp.newline("\t\t\t\tIFNULL(TRIM(CAST(FILEDATE AS STRING)), '') FILEDATE,")
        uniquesp.newline("\t\t\t\tIFNULL(TRIM(CAST(FILENAME AS STRING)), '') FILENAME,")
        uniquesp.newline("\t\t\t\tCAST(IFNULL(FILEROWNUMBER,0) AS NUMBER(38,0)) FILEROWNUMBER,")

        # add columns and cast to appropriate datatype
        for row in col_list:
            colname = str(row[1]).upper()
            datatype = str(row[2]).upper()

            # special handling for first name
            # if colname.upper() == 'FIRST_NAME':
            #     uniquesp.newline(f"\t\t\t\tSPLIT_PART(IFNULL(TRIM(CAST(NAME AS STRING)), ''), ' ', 0) FIRST_NAME,")
            # # special handling for middle name
            # elif colname.upper() == 'MIDDLE_NAME':
            #     uniquesp.newline(f"\t\t\t\tCASE")
            #     uniquesp.newline(f"\t\t\t\t\tWHEN NAME ILIKE '% % %'")
            #     uniquesp.newline(f"\t\t\t\t\tTHEN SPLIT_PART(IFNULL(TRIM(CAST(NAME AS STRING)), ''), ' ', 2)")
            #     uniquesp.newline(f"\t\t\t\t\tELSE ''")
            #     uniquesp.newline(f"\t\t\t\tEND MIDDLE_NAME,")
            # # special handling for last name
            # elif colname.upper() == 'LAST_NAME':
            #     uniquesp.newline(f"\t\t\t\tCASE")
            #     uniquesp.newline(f"\t\t\t\t\tWHEN NAME ILIKE '% % %'")
            #     uniquesp.newline(f"\t\t\t\t\tTHEN SPLIT_PART(IFNULL(TRIM(CAST(NAME AS STRING)), ''), ' ', 3)")
            #     uniquesp.newline(f"\t\t\t\t\tELSE")
            #     uniquesp.newline(f"\t\t\t\t\tCASE")
            #     uniquesp.newline(f"\t\t\t\t\t\tWHEN NAME ILIKE '% %'")
            #     uniquesp.newline(f"\t\t\t\t\t\tTHEN SPLIT_PART(IFNULL(TRIM(CAST(NAME AS STRING)), ''), ' ', 2)")
            #     uniquesp.newline(f"\t\t\t\t\tEND")
            #     uniquesp.newline(f"\t\t\t\tEND LAST_NAME,")
            if "TIMESTAMP" in datatype or "DATETIME" in datatype:
                if row[1] in pk_list:
                    uniquesp.newline(f"\t\t\t\tCAST(to_datetime(IFNULL({colname},'1900-01-01')) AS TIMESTAMP) {colname},")
                else:
                    uniquesp.newline(f"\t\t\t\tCAST(to_datetime({colname}) AS TIMESTAMP) {colname},")
            elif row[2].replace(" ", "").upper() == "NUMBER(38)" or row[2].replace(" ", "").upper() == "NUMBER(38,0)":
                if row[1] in pk_list:
                    uniquesp.newline(f"\t\t\t\tCAST(to_integer(IFNULL({colname},0)) AS INT) {colname},")
                else:
                    uniquesp.newline(f"\t\t\t\tCAST(to_integer({colname}) AS INT) {colname},")

            elif "NUMBER" in datatype:
                if row[1] in pk_list:
                    replacestr = remove_chars(colname, ["$", ",", " "])
                    uniquesp.newline(f"\t\t\t\tCAST(to_double(IFNULL(NULLIF({replacestr},''),0)) AS {row[2]}) {colname},")
                else:
                    replacestr = remove_chars(colname, ["$", ",", " "])
                    uniquesp.newline(f"\t\t\t\tCAST(to_double(IFNULL(NULLIF({replacestr},''),0)) AS {row[2]}) {colname},")

            elif "BOOLEAN" in datatype:
                if row[1] in pk_list:
                    uniquesp.newline(f"\t\t\t\tTRY_TO_BOOLEAN(CAST(IFNULL({colname},'0') AS VARCHAR)) {colname},")
                else:
                    uniquesp.newline(f"\t\t\t\tTRY_TO_BOOLEAN(CAST({colname} AS VARCHAR)) {colname},")
            elif "VARIANT" in datatype:
                uniquesp.newline(f"\t\t\t\tCAST({colname} AS VARIANT) {colname},")
            # treat everything else as varchar
            else:
                uniquesp.newline(f"\t\t\t\tIFNULL(TRIM(CAST({colname} AS STRING)), '') {colname},")

        if std_ind == "1":
            uniquesp.newline("\t\t\t\tCast(TO_INTEGER(STANDARDIZATIONROWID) AS INT) STANDARDIZATIONROWID,")

        uniquesp.newline("\t\t\t\tROW_NUMBER() OVER")
        uniquesp.newline("\t\t\t\t(PARTITION BY")

        # add primary key columns
        for row in col_list:
            colname = str(row[1]).upper()
            datatype = str(row[2]).upper()
            if row[1] in pk_list:
                if "TIMESTAMP" in datatype or "DATETIME" in datatype:
                    uniquesp.newline(f"\t\t\t\t\tCAST(to_datetime(IFNULL({colname},'1900-01-01')) AS TIMESTAMP),")

                elif "NUMBER(38)" in datatype or "NUMBER(38,0)" in datatype:
                    uniquesp.newline(f"\t\t\t\t\tCAST(to_integer(IFNULL({colname},0)) AS INT),")

                elif "NUMBER" in datatype:
                    replacestr = remove_chars(colname, ["$", ",", " "])
                    uniquesp.newline(f"\t\t\t\t\tCAST(to_double(IFNULL(NULLIF({replacestr},''),0)) AS {row[2]}),")

                elif "BOOLEAN" in datatype:
                    uniquesp.newline(f"\t\t\t\tTRY_TO_BOOLEAN(CAST(IFNULL({colname},'0') AS VARCHAR)),")

                # treat everything else as varchar
                else:
                    uniquesp.newline(f"\t\t\t\t\tLOWER(IFNULL(TRIM(CAST({colname} AS STRING)), '')),")

        # remove trailing comma
        uniquesp.trimend(1)

        uniquesp.newline("\t\t\t\t\tORDER BY")
        uniquesp.newline("\t\t\t\t\t\tto_datetime(FILEDATE) DESC,")
        uniquesp.newline("\t\t\t\t\t\tFILENAME DESC,")
        uniquesp.newline("\t\t\t\t\t\tFILEROWNUMBER DESC")
        uniquesp.newline("\t\t\t\t) therealrownumber")
        uniquesp.newline("\t\t\tFROM")

        uniquesp.newline(f"\t\t\t\t{table_schema}.{import_table_name}")

        uniquesp.newline("\t\t) a")
        uniquesp.newline("\t\tWHERE a.therealrownumber = 1;")

        uniquesp.newline(f"\tRETURN 'FINISHED CALLING STORED PROCEDURE sp_CreateTable{table_name.upper()}Unique';")
        uniquesp.newline("\tEND;")
        uniquesp.newline("$$;")

        # define output folder and filename
        filename = f"sp_createtable{table_name.lower()}unique.sql"
        output_folder = f"{db_folder}data_repo{os.sep}tmp{os.sep}"
        filewrite(folder=output_folder, filename=filename, content=uniquesp.out())
        print_section_detail(msg=f"TMPCREATETABLEUNIQUE - {filename}\nCreated in: {output_folder}", runlog=runlog)

        # write output repo files if repo_root_folder is not empty
        if repo_root_folder != "":
            datarepo_folder = f"{repo_root_folder}data{os.sep}warehouse{os.sep}{source_name.lower()}{os.sep}tmp{os.sep}{client.upper()}{os.sep}"
            filewrite(folder=datarepo_folder, filename=filename, content=uniquesp.out())
            print_section_detail(msg=f"TMPCREATETABLEUNIQUE - {filename}\nCreated in: {datarepo_folder}", runlog=runlog)

        return unique_sp_name

    return unique_sp_name