from Library.FunctionFiles.Functions import *

# ----------------------------------------------------------------
# Create CopyInto File
# ----------------------------------------------------------------
def fn_create_copyinto_custom(client:str, source_name:str, table_name:str, col_list:list, file_match_text:str, file_date_regex:str, field_delimiter:str, version:str, db_folder:str, runlog:object, field_enclosed_by:str, custom_fileformat_options:str, repo_root_folder:str, worksheet:object):
    # initialize CopyInto Document
    CopyInto = Document()

    # format custom_fileformat_options
    custom_fileformat_options = custom_fileformat_options.strip()

    if custom_fileformat_options == "None":
        custom_fileformat_options = ""
    elif custom_fileformat_options != '':
        custom_fileformat_options = f" {custom_fileformat_options}"
    else:
        custom_fileformat_options = ""

    # define stage location path
    stage_location = f"@&database.IMPORT.INGESTSTAGE/&feature/&teamAbbr/&timestamp"

    # initialize elements of the CopyInto statement
    CopyInto.append(f"/*{table_name} Copy Into version={version} generated by config generator */")
    CopyInto.newline(f"COPY INTO &database.import.{table_name.lower()}_raw")
    CopyInto.newline("(")
    CopyInto.newline("\tFILEDATE,")
    CopyInto.newline("\tFILENAME,")
    CopyInto.newline("\tFILEROWNUMBER,")
    CopyInto.newline("\tJSONDATA")
    CopyInto.newline(")")
    CopyInto.newline("FROM")
    CopyInto.newline("(")
    CopyInto.newline("\tSELECT")
    CopyInto.newline(
        f"\t\tTO_CHAR(REGEXP_SUBSTR(REPLACE(REPLACE(SPLIT_PART(METADATA$FILENAME, '/', -2),'_',''),'-',''), '{file_date_regex}', 1, 1)) FILEDATE,")
    CopyInto.newline("\t\tMETADATA$FILENAME,")
    CopyInto.newline("\t\tMETADATA$FILE_ROW_NUMBER,")
    CopyInto.newline("\t\tPARSE_JSON(T.\"$1\") AS JSONDATA")
    CopyInto.newline("\tFROM ")
    CopyInto.append(f"{stage_location} T")
    CopyInto.newline(")")
    CopyInto.newline(f"PATTERN = '{file_match_text}'")
    CopyInto.newline("ON_ERROR = CONTINUE")
    CopyInto.newline("FORCE = TRUE")
    CopyInto.newline(f"FILE_FORMAT = (TYPE = JSON STRIP_OUTER_ARRAY = TRUE{custom_fileformat_options})")
    CopyInto.newline(";")

    # define output folder and filename
    filename = f"{table_name.lower()}-copy.sql"
    output_folder = f"{db_folder}config_repo{os.sep}sources{os.sep}"
    filewrite(folder=output_folder, filename=filename, content=CopyInto.out())
    print_section_detail(msg=f"COPYINTO - {filename}\nCreated in: {output_folder}", runlog=runlog)

    # write output repo files if repo_root_folder is not empty
    if repo_root_folder != "":
        configrepo_folder = f"{repo_root_folder}kagr-configuration{os.sep}prefect{os.sep}{client.upper()}{os.sep}{source_name.lower()}{os.sep}sources{os.sep}"
        filewrite(folder=configrepo_folder, filename=filename, content=CopyInto.out())
        print_section_detail(msg=f"COPYINTO - {filename}\nCreated in: {configrepo_folder}", runlog=runlog)

    return filename