import copy

from SourcePlugins.Archtics.BusRule_ArchticsAttendance import *
from SourcePlugins.Archtics.BusRule_ArchticsAvailableInventory import *
from SourcePlugins.Archtics.BusRule_ArchticsHeldSeats import *
from SourcePlugins.Archtics.BusRule_ArchticsManifest import *
from SourcePlugins.Archtics.BusRule_ArchticsTicketExpanded import *
from SourcePlugins.Archtics.BusRule_ArchticsCustomerAddress import *
from SourcePlugins.Archtics.BusRule_ArchticsCustomerAlternateId import *
from SourcePlugins.Archtics.BusRule_ArchticsCustomerAttributes import *
from SourcePlugins.Archtics.BusRule_ArchticsCustomerRep import *
from SourcePlugins.Archtics.BusRule_ArchticsCustomerTrace import *
from SourcePlugins.Archtics.BusRule_ArchticsDonation import *
from SourcePlugins.Archtics.BusRule_ArchticsInvoiceLineItem import *
from SourcePlugins.Archtics.BusRule_ArchticsJournal import *
from SourcePlugins.Archtics.BusRule_ArchticsListCode import *
from SourcePlugins.Archtics.BusRule_ArchticsMemberships import *
from SourcePlugins.Archtics.BusRule_ArchticsNote import *
from SourcePlugins.Archtics.BusRule_ArchticsPaymentScheduleDetails import *
from SourcePlugins.Archtics.BusRule_ArchticsPromoCode import *
from SourcePlugins.Archtics.BusRule_ArchticsRetailNonTicket import *
from SourcePlugins.Archtics.BusRule_ArchticsSolicitations import *
from SourcePlugins.Archtics.BusRule_ArchticsTicketExchange import *
from SourcePlugins.Archtics.BusRule_ArchticsCustomerMerge import *
from SourcePlugins.Archtics.BusRule_ArchticsCustomers import *
from SourcePlugins.Archtics.ArchticsTicketExpandedColumns import *
from SourcePlugins.Archtics.ArchticsAppendColumns import *

# ----------------------------------------------------------------
# Set creation options
# ----------------------------------------------------------------
need_flatten = False
need_import_raw = False
need_create_std_busrule = False
need_create_stg_rawaud_busrule = False
need_create_tmp_rawaud_busrule = False

# ----------------------------------------------------------------
# Create CopyInto File-API
# ----------------------------------------------------------------
def fn_create_copyinto_custom_api(client:str, source_name:str, table_name:str, col_list:list, file_match_text:str, file_date_regex:str, version:str, db_folder:str, runlog:object, custom_fileformat_options:str, repo_root_folder:str, worksheet:object):
    runlog.log("Running Archtics-api specific copyinto function")

    # initialize CopyInto Document
    CopyInto = Document()

    # build column list
    copyintocolumns = []
    copyelements = []
    for col in col_list:
        copyintocolumns.append(f"\t{col[1].upper()}")
        copyelements.append(f"\t\tIFF(GET(\"$1\",'{col[0]}') IS NOT NULL,GET(\"$1\",'{col[0]}'),1/0)")

    # format custom_fileformat_options
    custom_fileformat_options = custom_fileformat_options.strip()

    if custom_fileformat_options == "None":
        custom_fileformat_options = ""
    elif custom_fileformat_options != '':
        custom_fileformat_options = f" {custom_fileformat_options}"
    else:
        custom_fileformat_options = ""

    # define stage location path
    stage_location = f"@&database.IMPORT.INGESTSTAGE/&feature/&teamAbbr"

    # override file_date_regex
    file_date_regex = "[0-9]{12}"

    # initialize elements of the CopyInto statement
    CopyInto.append(f"/*{table_name} Copy Into version={version} generated by config generator */")
    CopyInto.newline(f"COPY INTO &database.IMPORT.{table_name.upper()}")
    CopyInto.newline("(")
    CopyInto.newline("\tFILEDATE,")
    CopyInto.newline("\tFILENAME,")
    CopyInto.newline("\tFILEROWNUMBER,")
    CopyInto.newlinelist(copyintocolumns)
    CopyInto.newline(")")
    CopyInto.newline("FROM")
    CopyInto.newline("(")
    CopyInto.newline("\tSELECT")
    CopyInto.newline(f"\t\tTO_CHAR(REGEXP_SUBSTR(REPLACE(REPLACE(SPLIT_PART(METADATA$FILENAME, '/', -2),'_',''),'-',''), '{file_date_regex}', 1, 1)),")
    CopyInto.newline("\t\tMETADATA$FILENAME,")
    CopyInto.newline("\t\tMETADATA$FILE_ROW_NUMBER,")
    CopyInto.newlinelist(copyelements)
    CopyInto.newline("\tFROM ")
    CopyInto.append(f"{stage_location} T")
    CopyInto.newline(")")
    CopyInto.newline(f"PATTERN = '{file_match_text}'")
    CopyInto.newline("ON_ERROR = CONTINUE")
    CopyInto.newline("FORCE = TRUE")
    CopyInto.newline(f"FILE_FORMAT = (TYPE = JSON STRIP_OUTER_ARRAY = TRUE{custom_fileformat_options})")
    CopyInto.newline(";")

    # define output folder and filename
    filename = f"{table_name.lower()}-copy-api.sql"
    output_folder = f"{db_folder}config_repo{os.sep}sources{os.sep}"

    # write output repo files if repo_root_folder is not empty
    if repo_root_folder != "":
        configrepo_folder = f"{repo_root_folder}kagr-configuration{os.sep}prefect{os.sep}{client.upper()}{os.sep}{source_name.lower()}{os.sep}sources{os.sep}"

    # write copyinto to file
    filewrite(folder=output_folder, filename=filename, content=CopyInto.out())
    print_section_detail(msg=f"COPYINTO - {filename}\nCreated in: {output_folder}", runlog=runlog)

    # write output repo files if repo_root_folder is not empty
    if repo_root_folder != "":
        filewrite(folder=configrepo_folder, filename=filename, content=CopyInto.out())
        print_section_detail(msg=f"COPYINTO - {filename}\nCreated in: {configrepo_folder}", runlog=runlog)

    runlog.log("")
    return filename

# ----------------------------------------------------------------
# Create CopyInto File-FF
# ----------------------------------------------------------------
def fn_create_copyinto_custom_ff(client:str, source_name:str, table_name:str, col_list:list, file_match_text:str, file_date_regex:str, field_delimiter:str, version:str, db_folder:str, runlog:object, field_enclosed_by:str, custom_fileformat_options:str, repo_root_folder:str, worksheet:object):
    runlog.log("Running Archtics-FF specific copyinto function")

    # initialize CopyInto Document
    CopyInto = Document()

    # build column list
    copyintocolumns = []
    copyelements = []
    colIndex = 1
    for col in col_list:
        copyintocolumns.append(f"\t{col[1].upper()}")
        copyelements.append(f"\t\tT.\"${colIndex}\"")
        colIndex += 1

    # format custom_fileformat_options
    custom_fileformat_options = custom_fileformat_options.strip()

    if custom_fileformat_options == "None":
        custom_fileformat_options = ""
    elif custom_fileformat_options != '':
        custom_fileformat_options = f" {custom_fileformat_options}"
    else:
        custom_fileformat_options = ""

    # define stage location path
    stage_location = f"@&database.IMPORT.INGESTSTAGE/&feature/&teamAbbr/&timestamp/archtics_sftp"

    # initialize elements of the CopyInto statement
    CopyInto.append(f"/*{table_name} Copy Into version={version} generated by config generator */")
    CopyInto.newline(f"COPY INTO &database.IMPORT.{table_name.upper()}")
    CopyInto.newline("(")
    CopyInto.newline("\tFILEDATE,")
    CopyInto.newline("\tFILENAME,")
    CopyInto.newline("\tFILEROWNUMBER,")
    CopyInto.newlinelist(copyintocolumns)
    CopyInto.newline(")")
    CopyInto.newline("FROM")
    CopyInto.newline("(")
    CopyInto.newline("\tSELECT")
    CopyInto.newline(f"\t\tTO_CHAR(REGEXP_SUBSTR(REPLACE(REPLACE(SPLIT_PART(METADATA$FILENAME, '/', -1),'_',''),'-',''), '{file_date_regex}', 1, 1)),")
    CopyInto.newline("\t\tMETADATA$FILENAME,")
    CopyInto.newline("\t\tMETADATA$FILE_ROW_NUMBER,")
    CopyInto.newlinelist(copyelements)
    CopyInto.newline("\tFROM ")
    CopyInto.append(f"{stage_location} T")
    CopyInto.newline(")")
    CopyInto.newline(f"PATTERN = '{file_match_text}'")
    CopyInto.newline("ON_ERROR = CONTINUE")
    CopyInto.newline("FORCE = TRUE")
    CopyInto.newline(f"FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = '\\t' TRIM_SPACE = TRUE SKIP_HEADER = 1 ENCODING = 'utf-8' ESCAPE_UNENCLOSED_FIELD = NONE{custom_fileformat_options})")
    CopyInto.newline(";")

    # define output folder and filename
    filename = f"{table_name.lower()}_sftp-copy.sql"
    output_folder = f"{db_folder}config_repo{os.sep}sources{os.sep}"

    # write output repo files if repo_root_folder is not empty
    if repo_root_folder != "":
        configrepo_folder = f"{repo_root_folder}kagr-configuration{os.sep}prefect{os.sep}{client.upper()}{os.sep}{source_name.lower()}{os.sep}sources{os.sep}"

    # write copyinto to file
    filewrite(folder=output_folder, filename=filename, content=CopyInto.out())
    print_section_detail(msg=f"COPYINTO - {filename}\nCreated in: {output_folder}", runlog=runlog)

    # write output repo files if repo_root_folder is not empty
    if repo_root_folder != "":
        filewrite(folder=configrepo_folder, filename=filename, content=CopyInto.out())
        print_section_detail(msg=f"COPYINTO - {filename}\nCreated in: {configrepo_folder}", runlog=runlog)

    runlog.log("")
    return filename

# ----------------------------------------------------------------
# Create CopyInto File
# ----------------------------------------------------------------
def fn_create_copyinto_custom(client:str, source_name:str, table_name:str, col_list:list, file_match_text:str, file_date_regex:str, field_delimiter:str, version:str, db_folder:str, runlog:object, field_enclosed_by:str, custom_fileformat_options:str, repo_root_folder:str, worksheet:object):
    if source_name.upper() == "ARCHTICS-API":
        copyinto_filename = fn_create_copyinto_custom_api(client=client, source_name=source_name, table_name=table_name.lower(), col_list=col_list, file_match_text=file_match_text, file_date_regex=file_date_regex, version=version, db_folder=db_folder, runlog=runlog, repo_root_folder=repo_root_folder, custom_fileformat_options=custom_fileformat_options, worksheet=worksheet)
    else:
        copyinto_filename = fn_create_copyinto_custom_ff(client=client, source_name=source_name, table_name=table_name.lower(), col_list=col_list, file_match_text=file_match_text, file_date_regex=file_date_regex, field_delimiter=field_delimiter, version=version, db_folder=db_folder, runlog=runlog, repo_root_folder=repo_root_folder, field_enclosed_by=field_enclosed_by, custom_fileformat_options=custom_fileformat_options, worksheet=worksheet)

    return copyinto_filename

# ----------------------------------------------------------------
# Append Business Rules
# ----------------------------------------------------------------
def fn_busrules_append(worksheet:object, bus_rule_obj:object, db_folder:str, runlog:object):
    runlog.log("Running Archtics specific busrules append function")

    # get table name
    table_name = worksheet.table_name()

    # get columns
    col_list = worksheet.columns()

    # get primary keys
    pk = worksheet.primary_keys()

    # ----------------------------------------------------------------
    # Archtics Attendance
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSATTENDANCE":
        archticsattendance_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics AvailableInventory
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSAVAILABLEINVENTORY":
        archticsavailableinventory_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics HeldSeats
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSHELDSEATS":
        archticsheldseats_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Manifest
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSMANIFEST":
        archticsmanifest_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Customer Address
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSCUSTOMERADDRESS":
        archticscustomeraddress_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Customer Alternateid
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSCUSTOMERALTERNATEID":
        archticscustomeralternateid_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Customer Attributes
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSCUSTOMERATTRIBUTES":
        archticscustomerattributes_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Customer Merge
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSCUSTOMERMERGE":
        archticscustomermerge_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Customer Rep
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSCUSTOMERREP":
        archticscustomerrep_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder,runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Customers
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSCUSTOMERS":
        archticscustomers_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Customer Trace
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSCUSTOMERTRACE":
        archticscustomertrace_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Donation
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSDONATION":
        archticsdonation_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Invoice Line Item
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSINVOICELINEITEM":
        archticsinvoicelineitem_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Journal
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSJOURNAL":
        archticsjournal_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics List Code
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSLISTCODE":
        archticslistcode_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Memberships
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSMEMBERSHIPS":
        archticsmemberships_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Note
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSNOTE":
        archticsnote_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Payment Schedule Details
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSPAYMENTSCHEDULEDETAILS":
        archticspaymentscheduledetails_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Promo Code
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSPROMOCODE":
        archticspromocode_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Retail Non Ticket
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSRETAILNONTICKET":
        archticsretailnonticket_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Solicitations
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSSOLICITATIONS":
        archticssolicitations_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Ticket Exchange
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSTICKETEXCHANGE":
        archticsticketexchange_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    # ----------------------------------------------------------------
    # Archtics Ticket Expanded
    # ----------------------------------------------------------------
    if table_name.upper() == "ARCHTICSTICKETEXPANDED":
        archticsticketexpanded_busrules(col_list=col_list, pk=pk, bus_rule_obj=bus_rule_obj, db_folder=db_folder, runlog=runlog)

    runlog.log("")
    return

# ----------------------------------------------------------------
# Append File Transfers
# ----------------------------------------------------------------
def fn_file_transfers_append(file_transfers_obj:object, client_project:str, runlog:object):
    runlog.log("Running Archtics specific file_transfers append function")

    file_transfers_obj.append("ASYNC_ARCHIVE", "true")
    file_transfers_obj.append("MASTERSCHEDULE", f"../{client_project}/Archtics_API_Master")

    runlog.log("")
    return

# ----------------------------------------------------------------
# Create TMP DDL
# ----------------------------------------------------------------
def create_tmp_deletes_ddl(StageDDL:object, client:str, source_name:str, stg_table_names:list, tmp_table_name:str, pk_str:str, db_folder:str, repo_root_folder:str, runlog:object, customreplace:list=[]):
    TmpDeleteDDL = copy.deepcopy(StageDDL)
    TmpDeleteDDL.replace("STAGE", "TMP")
    TmpDeleteDDL.replace("Stage", "Tmp")
    for tblname in stg_table_names:
        TmpDeleteDDL.replace(tblname, tmp_table_name)

    TmpDeleteDDL.replace("DWUPDATEDATE\tTIMESTAMP_LTZ(9),",
                         "DWUPDATEDATE\tTIMESTAMP_LTZ(9),\n\tDELETEDATETIME\tTIMESTAMP_LTZ(9)")
    TmpDeleteDDL.replace(f"\n\t{pk_str}", "")

    # custom replace is a list of items to replace.
    # Item should be a list with index 0 the string to find and index 1 the string to replace with
    if len(customreplace) > 0:
        for item in customreplace:
            TmpDeleteDDL.replace(item[0], item[1])


    # define output folder and filename
    filename = f"{tmp_table_name.lower()}.sql"
    output_folder = f"{db_folder}data_repo{os.sep}tmp{os.sep}"
    filewrite(folder=output_folder, filename=filename, content=TmpDeleteDDL.out())
    print_section_detail(msg=f"TMP DDL - {filename}\nCreated in: {output_folder}", runlog=runlog)

    # write output repo files if repo_root_folder is not empty
    if repo_root_folder != "":
        datarepo_folder = f"{repo_root_folder}data{os.sep}warehouse{os.sep}{source_name.lower()}{os.sep}tmp{os.sep}{client.upper()}{os.sep}"
        filewrite(folder=datarepo_folder, filename=filename, content=TmpDeleteDDL.out())
        print_section_detail(msg=f"TMP DDL - {filename}\nCreated in: {datarepo_folder}", runlog=runlog)
        
    return

# ----------------------------------------------------------------
# Create Stage Dedup table
# ----------------------------------------------------------------
def create_stg_dedup_ddl(client: str, source_name: str, table_name:str, col_list:list, db_folder:str, repo_root_folder:str, runlog:object, ):
    # STAGE - read column list and datatype and create column list for table creation
    stagecolumns = getDDLcolumns(col_list=col_list, ddl_type="stage", phone_col_list=[], email_col_list=[])

    # initialize Stage DDL document
    StageDDL = Document()

    # create complete import DDL per table
    StageDDL.append(
        f"/*{table_name} (Stage) grantObjectName={table_name} version=1 generated by config generator */")
    StageDDL.newline(f"CREATE TABLE IF NOT EXISTS STAGE.{table_name.upper()}")
    StageDDL.newline("(")
    StageDDL.newlinelist(stagecolumns)
    StageDDL.newline(");")

    # define output folder and filename
    filename = f"{table_name.lower()}.sql"
    output_folder = f"{db_folder}data_repo{os.sep}stage{os.sep}"
    filewrite(folder=output_folder, filename=filename, content=StageDDL.out())
    print_section_detail(msg=f"STAGE DDL - {filename}\nCreated in: {output_folder}", runlog=runlog)

    # write output repo files if repo_root_folder is not empty
    if repo_root_folder != "":
        datarepo_folder = f"{repo_root_folder}data{os.sep}warehouse{os.sep}{source_name.lower()}{os.sep}stage{os.sep}{client.upper()}{os.sep}"
        filewrite(folder=datarepo_folder, filename=filename, content=StageDDL.out())
        print_section_detail(msg=f"STAGE DDL - {filename}\nCreated in: {datarepo_folder}", runlog=runlog)

    return

# ----------------------------------------------------------------
# Create Stage Snapshot table
# ----------------------------------------------------------------
def create_stg_snapshot_ddl(StageDDL:object, client:str, source_name:str, stg_table_names:list, snapshot_table_name:str, pk_str:str, db_folder:str, repo_root_folder:str, runlog:object, customreplace: list = []):
    SnapshotDDL = copy.deepcopy(StageDDL)
    for tblname in stg_table_names:
        SnapshotDDL.replace(tblname, snapshot_table_name)

    if "AVAILABLEINVENTORY" in snapshot_table_name:
        SnapshotDDL.replace("FILEDATE", "INVENTORYHASH\tVARCHAR,\n\tINVENTORYRUNDATETIMEFROM\tTIMESTAMP_LTZ(9)\tNOT NULL,\n\tINVENTORYRUNDATETIMETO\tTIMESTAMP_LTZ(9)\tNOT NULL,\n\tFILEDATE")
    elif "HELDSEATS" in snapshot_table_name:
        SnapshotDDL.replace("FILEDATE", "HELDSEATSHASH\tVARCHAR,\n\tHELDSEATSRUNDATETIMEFROM\tTIMESTAMP_LTZ(9)\tNOT NULL,\n\tHELDSEATSRUNDATETIMETO\tTIMESTAMP_LTZ(9)\tNOT NULL,\n\tFILEDATE")

    SnapshotDDL.replace(f"\n\t{pk_str}", "")
    SnapshotDDL.replace(",\n);", "\n);")

    # custom replace is a list of items to replace.
    # Item should be a list with index 0 the string to find and index 1 the string to replace with
    if len(customreplace) > 0:
        for item in customreplace:
            SnapshotDDL.replace(item[0], item[1])

    # define output folder and filename
    filename = f"{snapshot_table_name.lower()}.sql"
    output_folder = f"{db_folder}data_repo{os.sep}stage{os.sep}"
    filewrite(folder=output_folder, filename=filename, content=SnapshotDDL.out())
    print_section_detail(msg=f"STAGE DDL - {filename}\nCreated in: {output_folder}", runlog=runlog)

    # write output repo files if repo_root_folder is not empty
    if repo_root_folder != "":
        datarepo_folder = f"{repo_root_folder}data{os.sep}warehouse{os.sep}{source_name.lower()}{os.sep}stage{os.sep}{client.upper()}{os.sep}"
        filewrite(folder=datarepo_folder, filename=filename, content=SnapshotDDL.out())
        print_section_detail(msg=f"STAGE DDL - {filename}\nCreated in: {datarepo_folder}", runlog=runlog)

    return

# ----------------------------------------------------------------
# Create Stage DDL
# ----------------------------------------------------------------
def fn_create_stage_DDL_custom(table_name:str, col_list:list, pk_str:str, phone_col_list:list, std_ind:int, rawaud_ind:int, version:str, db_folder:str, runlog:object, repo_root_folder:str, client:str, source_name:str, data_resources:list, email_col_list:list=[]):

    # generate primary key list
    pk_str = pk_str.replace("PRIMARY KEY (","").replace(")","")
    pk_list = pk_str.split(",")

    # add columns
    pk_list, col_list = table_append_columns(table_name=table_name, pk_list=pk_list, col_list=col_list)

    # remove Keyhash if its in pk, as it will be added by the DDL creator
    if "KEYHASH" in pk_list:
        for col in col_list:
            if "KEYHASH" in col:
                col_list.remove(col)

    if rawaud_ind == "1":
        col_list.remove(["", "RAWAUDIENCEID", "NUMBER(38,0)"])

    # generate concatenated Primary Key columns string
    primary_keys = ""
    for pk in pk_list:
        primary_keys += f"{str(pk.strip()).upper()},"

    # strip out command new line character from last row
    primary_keys = primary_keys[:-1]

    pk_str = f"PRIMARY KEY ({primary_keys})"


    StageDDL_str, StageArchive_DDL = create_stage_DDL(table_name=table_name.lower(), col_list=col_list, pk_str=pk_str, phone_col_list=phone_col_list, std_ind=std_ind, rawaud_ind=rawaud_ind, version=version, db_folder=db_folder, runlog=runlog, repo_root_folder=repo_root_folder, client=client, source_name="archtics", email_col_list=email_col_list)

    StageDDL = Document()
    StageDDL.newline(StageDDL_str)

    # ARCHTICSAVAILABLEINVENTORY
    if table_name.upper() == "ARCHTICSAVAILABLEINVENTORY":
        tmp_table_name = "AVAILINVENTORY_DELETES"
        snapshot_table_name = f"{table_name.upper()}SNAPSHOT"
        stg_table_names = ["ARCHTICSAVAILABLEINVENTORY", "ArchticsAvailableInventory", "archticsavailableinventory"]

        # tmp deletes
        create_tmp_deletes_ddl(StageDDL=StageDDL, client=client, source_name="archtics", stg_table_names=stg_table_names, tmp_table_name=tmp_table_name, pk_str=pk_str, db_folder=db_folder, repo_root_folder=repo_root_folder, runlog=runlog)
        # append data resources
        data_resources.append(["tmp", tmp_table_name.lower()])

        # snapshot
        create_stg_snapshot_ddl(StageDDL=StageDDL, client=client, source_name="archtics", stg_table_names=stg_table_names, snapshot_table_name=snapshot_table_name, pk_str=pk_str, db_folder=db_folder, repo_root_folder=repo_root_folder, runlog=runlog)
        # append data resources
        data_resources.append(["stage", snapshot_table_name.lower()])

    # ARCHTICSHELDSEATS
    if table_name.upper() == "ARCHTICSHELDSEATS":
        tmp_table_name = "HELDSEATS_DELETES"
        snapshot_table_name = f"{table_name.upper()}SNAPSHOT"
        stg_table_names = ["ARCHTICSHELDSEATS", "ArchticsHeldSeats", "archticsheldseats"]

        # tmp deletes
        create_tmp_deletes_ddl(StageDDL=StageDDL, client=client, source_name="archtics", stg_table_names=stg_table_names, tmp_table_name=tmp_table_name, pk_str=pk_str, db_folder=db_folder, repo_root_folder=repo_root_folder, runlog=runlog)
        # append data resources
        data_resources.append(["tmp", tmp_table_name.lower()])

        # snapshot
        create_stg_snapshot_ddl(StageDDL=StageDDL, client=client, source_name="archtics", stg_table_names=stg_table_names, snapshot_table_name=snapshot_table_name, pk_str=pk_str, db_folder=db_folder, repo_root_folder=repo_root_folder, runlog=runlog)
        # append data resources
        data_resources.append(["stage", snapshot_table_name.lower()])

    # ARCHTICSTICKETEXPANDED
    if table_name.upper() == "ARCHTICSTICKETEXPANDED":
        dedup_table_name = f"{table_name.upper()}DEDUP"
        col_list = []
        for col in ArchticsTicketExpandedColumns:
            if "INSERT" in col[2]:
                col_list.append([col[0], col[0], col[1]])

        # dedup
        create_stg_dedup_ddl(client=client, source_name="archtics", table_name=dedup_table_name, col_list=col_list, db_folder=db_folder, repo_root_folder=repo_root_folder, runlog=runlog)
        # append data resources
        data_resources.append(["stage", dedup_table_name.lower()])

    # Generate Tmp ManifestDeletes
    if table_name.upper() == "ARCHTICSMANIFEST":
        tmp_table_name = "MANIFEST_DELETES"
        stg_table_names = ["ARCHTICSMANIFEST", "ArchticsManifest", "archticsmanifest"]
        create_tmp_deletes_ddl(StageDDL=StageDDL, client=client, source_name="archtics", stg_table_names=stg_table_names, tmp_table_name=tmp_table_name, pk_str=pk_str, db_folder=db_folder, repo_root_folder=repo_root_folder, runlog=runlog)

        # append data resources
        data_resources.append(["tmp", "manifest_deletes"])

    # append data resources
    data_resources.append(["stage", table_name.lower()])

    # return StageDDL
    return StageDDL.out(), data_resources

# ----------------------------------------------------------------
# Create unique tmp table SP
# ----------------------------------------------------------------
def fn_create_unique_sp_custom(table_name:str, pk_list:list, col_list:list, db_folder:str, runlog:object, std_ind:str, repo_root_folder:str, client:str, source_name:str, import_view_name:str="", create_keyhash:str="0"):

    runlog.log("Running Archtics Create Unique SP")
    table_name = table_name.upper()

    sp_tablename, pk_list, col_list_list = unique_sp_append_columns(table_name=table_name, pk_list=pk_list, col_list=col_list)

    unique_sp_name = create_unique_sp(table_name=table_name, pk_list=pk_list, col_list=col_list_list, db_folder=db_folder, runlog=runlog, std_ind=std_ind, repo_root_folder=repo_root_folder, client=client, source_name="archtics", import_view_name=sp_tablename)

    return unique_sp_name

# ----------------------------------------------------------------
# Create merge SP
# ----------------------------------------------------------------
def fn_create_merge_sp_custom(table_name:str, pk_list:list, col_list:list, db_folder:str, runlog:object, std_ind:str, repo_root_folder:str, client:str, source_name:str, create_keyhash:str="0"):
    runlog.log("Running Archtics Create Merge SP")

    pk_list, col_list = table_append_columns(table_name=table_name, pk_list=pk_list, col_list=col_list)

    if std_ind == "1":
        col_list.remove(["", "RAWAUDIENCEID", "NUMBER(38,0)"])

    merge_sp_name = create_merge_sp(table_name=table_name, pk_list=pk_list, col_list=col_list, db_folder=db_folder, runlog=runlog, std_ind=std_ind, repo_root_folder=repo_root_folder, client=client, source_name="archtics")

    return merge_sp_name

# ----------------------------------------------------------------
# Create Import DDL
# ----------------------------------------------------------------
def fn_create_import_DDL_custom(table_name:str, col_list:list, version:str, db_folder:str, runlog:object, repo_root_folder:str, client:str, source_name:str, data_resources:list):
    create_import_DDL(table_name=table_name.lower(), col_list=col_list, version=version, db_folder=db_folder, runlog=runlog, repo_root_folder=repo_root_folder, client=client, source_name="archtics")
    # append data resources
    data_resources.append(["import", table_name.lower()])

    return
