from Library.FunctionFiles.Functions import *

# ----------------------------------------------------------------
# Create CopyInto File
# ----------------------------------------------------------------
def fn_create_flatten_custom(source_name:str, table_name:str, table_name_raw:str, col_list:list, version:str, db_folder:str, runlog:object, repo_root_folder:str, client:str, worksheet: object):
    runlog.log("Running Axs specific copy into function to generate insert into")

    # initialize CopyInto Document
    Flatten = Document()

    # build column list
    insertintocolumns = []
    insertelements = []
    for col in col_list:
        insertintocolumns.append(f"\t{col[1].upper()}")
        insertelements.append(f"\t{col[0].upper()}")

    # define source table
    try:
        source_table = worksheet.tableinfo()["SourceTableName"].strip()
    except Exception as e:
        runlog.log("SourceTableName not found in table info")
        raise Exception("SourceTableName not found in table info")

    # define sourcedateindicator
    try:
        source_date = worksheet.tableinfo()["SourceDateIndicator"].strip()
    except Exception as e:
        runlog.log("SourceDateIndicator not found in table info")
        raise Exception("SourceDateIndicator not found in table info")

    # initialize elements of the CopyInto statement
    Flatten.append(f"/*{table_name} Insert Into version={version} generated by config generator */")
    Flatten.newline(f"INSERT INTO &database.IMPORT.{table_name.upper()}")
    Flatten.newline("(")
    Flatten.newline("\tFILEDATE,")
    Flatten.newline("\tFILENAME,")
    Flatten.newline("\tFILEROWNUMBER,")
    Flatten.newlinelist(insertintocolumns)
    Flatten.newline(")")
    Flatten.newline("SELECT")
    Flatten.newline(f"\tTO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MI'),")
    Flatten.newline("\t'',")
    Flatten.newline("\t0,")
    Flatten.newlinelist(insertelements)
    Flatten.newline(f"FROM AXSNCAA.{source_table}")
    if source_date != 'FULLPULL':
        Flatten.newline(f"WHERE {source_date} >= (")
        Flatten.newline(f"\tSELECT COALESCE(MAX({source_date}), '1900-01-01') FROM &database.STAGE.{table_name.upper()}")
        Flatten.newline(")")
    Flatten.newline(";")

    # define output folder and filename
    filename = f"{table_name.lower()}-insert.sql"
    output_folder = f"{db_folder}config_repo{os.sep}sources{os.sep}"

    # write output repo files if repo_root_folder is not empty
    if repo_root_folder != "":
        configrepo_folder = f"{repo_root_folder}kagr-configuration{os.sep}prefect{os.sep}{client.upper()}{os.sep}{source_name.lower()}{os.sep}sources{os.sep}"

    # write copyinto to file
    filewrite(folder=output_folder, filename=filename, content=Flatten.out())
    print_section_detail(msg=f"INSERTINTO - {filename}\nCreated in: {output_folder}", runlog=runlog)

    if repo_root_folder != "":
        filewrite(folder=configrepo_folder, filename=filename, content=Flatten.out())
        print_section_detail(msg=f"INSERTINTO - {filename}\nCreated in: {configrepo_folder}", runlog=runlog)

    return filename