from Library.FunctionFiles.Functions import *

# flattenjson
def flattenjson_personinfo(table_name:str, table_name_raw:str, col_list:list):
    jsonelements = []
    flattendoc = Document()

    # create JSON elements list
    for col in col_list:
        if col[1].upper() != "FIRSTNAME" and col[1].upper() != "LASTNAME":
            jsonelements.append(f"\t\traw.JSONDATA:{col[0]}::STRING AS {col[1].upper()}")

    jsonelements.append(f"\t\traw.JSONDATA:user_property.id::STRING AS USER_PROPERTY_ID")
    jsonelements.append(f"\t\traw.JSONDATA:user_property.name::STRING AS USER_PROPERTY_NAME")
    jsonelements.append(f"\t\traw.JSONDATA:user_property.value::STRING AS USER_PROPERTY_VALUE")

    # build flatten query
    flattendoc.append("\tSELECT")
    flattendoc.newline("\t\traw.FILEDATE,")
    flattendoc.newline("\t\traw.FILENAME,")
    flattendoc.newline("\t\traw.FILEROWNUMBER,")
    flattendoc.newlinelist(jsonelements)
    flattendoc.newline(f"\tFROM &database.IMPORT.ATTENTIVECUSTOMATTRIBUTEEVENTS_RAW raw")
    flattendoc.newline(f"\tWHERE")
    flattendoc.newline(f"\t\t(")
    flattendoc.newline(f"\t\t\tJSONDATA ILIKE '%FirstName%'")
    flattendoc.newline(f"\t\t\tOR JSONDATA ILIKE '%LastName%'")
    flattendoc.newline(f"\t\t\tOR JSONDATA ILIKE '%First Name%'")
    flattendoc.newline(f"\t\t\tOR JSONDATA ILIKE '%Last Name%'")
    flattendoc.newline(f"\t\t\tOR JSONDATA ILIKE '%email%'")
    flattendoc.newline(f"\t\t\tOR JSONDATA ILIKE '%phone%'")
    flattendoc.newline(f"\t\t)")
    flattendoc.newline("\t\tAND TO_TIMESTAMP(RPAD(raw.FILEDATE,14,'0'), 'YYYYMMDDHH24MISS') >")
    flattendoc.newline("\t\t(")
    flattendoc.newline(f"\t\t\tSELECT IFNULL(MAX(TO_TIMESTAMP(RPAD(FILEDATE,14,'0'), 'YYYYMMDDHH24MISS')),TO_TIMESTAMP('1900-01-01'))")
    flattendoc.newline(f"\t\t\tFROM &database.STAGE.{table_name.upper()}")
    flattendoc.newline("\t\t)")

    return flattendoc.out()

# Sources specific flatten
def fn_create_flatten_custom(source_name:str, table_name:str, table_name_raw:str, col_list:list, version:str, db_folder:str, runlog:object, repo_root_folder:str, client:str, worksheet: object):
    runlog.log("Running Attentive specific flatten function")

    # initialize Flatten Document
    Flatten = Document()
    insertcolumns = []
    pivotselect = []
    pivotresultselect = []
    ctebaseselect = ['TIMESTAMP', 'COMPANY_DISPLAY_NAME', 'COMPANY_COMPANY_ID', 'SUBSCRIBER_EXTERNAL_ID']
    nameselect = ctebaseselect[:]
    phoneselect = ctebaseselect[:]
    emailselect = ctebaseselect[:]

    nameselect.extend(["USER_PROPERTY_NAME", "USER_PROPERTY_VALUE"])
    nameselectupper = []
    for col in nameselect:
        if col != "USER_PROPERTY_NAME":
            nameselectupper.append(col)
        else:
            nameselectupper.append(f"UPPER(REPLACE(TRIM({col}),' ')) AS {col}")

    phoneselect.append("SUBSCRIBER_PHONE")
    emailselect.append("SUBSCRIBER_EMAIL")

    ctebaseselectformatted = []
    finalselectformatted = []

    for col in ctebaseselect:
        if col == "TIMESTAMP":
            ctebaseselectformatted.append(col)
        elif col == "COMPANY_DISPLAY_NAME" or col == "COMPANY_COMPANY_ID":
            ctebaseselectformatted.append(f"NULLIF({col},'') AS {col}")
            finalselectformatted.append(f"COALESCE(NM.{col}, PH.{col}, EM.{col}) AS {col}")
        elif col == "SUBSCRIBER_EXTERNAL_ID":
            ctebaseselectformatted.append(col)
            finalselectformatted.append(f"NM.{col}")
        else:
            ctebaseselectformatted.append(col)
            finalselectformatted.append(col)

    for col in nameselect:
        if col not in ctebaseselect:
            finalselectformatted.append(f"NM.{col}")

    for col in phoneselect:
        if col not in ctebaseselect:
            finalselectformatted.append(f"&database.public.fn_phoneformatter(NULLIF(PH.{col.upper()},'')) AS {col.upper()}")

    for col in emailselect:
        if col not in ctebaseselect:
            finalselectformatted.append(f"EM.{col}")

    # create column list for insert and json sections
    for col in col_list:
        # append columns into insert list
        insertcolumns.append(f"\t{col[1].upper()}")
        if col[1].upper() == "TIMESTAMP":
            pivotselect.append(f"\tTO_TIMESTAMP(TO_VARCHAR(MAX(FL.TIMESTAMP::Timestamp), 'yyyy-mm-dd hh:ss')) AS TIMESTAMP")
        else:
            pivotselect.append(f"\tPR.{col[1].upper()}")
            pivotresultselect.append(f"\t{col[1].upper()}")

    # initialize elements of insert statement
    Flatten.append(f"/*{table_name} Flatten Insert version={version} generated by config generator */")
    Flatten.newline(f"INSERT INTO &database.IMPORT.{table_name.upper()}")
    Flatten.newline("(")
    Flatten.newline("\tFILEDATE,")
    Flatten.newline("\tFILENAME,")
    Flatten.newline("\tFILEROWNUMBER,")
    Flatten.newlinelist(insertcolumns)
    Flatten.newline(")")
    # FLATTENJSON
    Flatten.newline(f"WITH FLATTENJSON AS")
    Flatten.newline("(")

    if table_name.upper()=="ATTENTIVEPERSONINFO":
        Flatten.newline(flattenjson_personinfo(table_name, table_name_raw, col_list))

    Flatten.newline("),")

    # MOSTRECENTFIRSTNAME
    Flatten.newline("MOSTRECENTFIRSTNAME AS (")
    Flatten.newline("\tSELECT")
    Flatten.newlinelist(str_list=nameselectupper, padding="\t\t")
    Flatten.newline("\tFROM FLATTENJSON")
    Flatten.newline("\tWHERE UPPER(REPLACE(TRIM(USER_PROPERTY_NAME),' ')) = 'FIRSTNAME'")
    Flatten.newline("\tQUALIFY ROW_NUMBER() OVER (PARTITION BY ")
    Flatten.newline("\t\tSUBSCRIBER_EXTERNAL_ID, USER_PROPERTY_NAME")
    Flatten.newline("\tORDER BY TIMESTAMP DESC) = 1")
    Flatten.newline("),")

    # MOSTRECENTLASTNAME
    Flatten.newline("MOSTRECENTLASTNAME AS (")
    Flatten.newline("\tSELECT")
    Flatten.newlinelist(str_list=nameselectupper, padding="\t\t")
    Flatten.newline("\tFROM FLATTENJSON")
    Flatten.newline("\tWHERE UPPER(REPLACE(TRIM(USER_PROPERTY_NAME),' ')) = 'LASTNAME'")
    Flatten.newline("\tQUALIFY ROW_NUMBER() OVER (PARTITION BY ")
    Flatten.newline("\t\tSUBSCRIBER_EXTERNAL_ID, USER_PROPERTY_NAME")
    Flatten.newline("\tORDER BY TIMESTAMP DESC) = 1")
    Flatten.newline("),")

    # MOSTRECENTNAME
    Flatten.newline("MOSTRECENTNAME AS (")
    Flatten.newline("\tSELECT")
    Flatten.newlinelist(str_list=ctebaseselectformatted, padding="\t\t")
    Flatten.newline("\t\t,USER_PROPERTY_NAME")
    Flatten.newline("\t\t,USER_PROPERTY_VALUE")
    Flatten.newline("\tFROM(")
    Flatten.newline("\tSELECT")
    Flatten.newlinelist(str_list=nameselect, padding="\t\t")
    Flatten.newline("\tFROM MOSTRECENTFIRSTNAME")
    Flatten.newline("\tUNION ALL")
    Flatten.newline("\tSELECT")
    Flatten.newlinelist(str_list=nameselect, padding="\t\t")
    Flatten.newline("\tFROM MOSTRECENTLASTNAME")
    Flatten.newline("\t)")
    Flatten.newline("),")

    # MOSTRECENTPHONE
    Flatten.newline("MOSTRECENTPHONE AS (")
    Flatten.newline("\tSELECT")
    Flatten.newlinelist(str_list=ctebaseselectformatted, padding="\t\t")
    Flatten.newline("\t\t,SUBSCRIBER_PHONE")
    Flatten.newline("\tFROM FLATTENJSON")
    Flatten.newline("\tWHERE LEN(SUBSCRIBER_PHONE) > 1")
    Flatten.newline("\tQUALIFY ROW_NUMBER() OVER (")
    Flatten.newline("\t\tPARTITION BY SUBSCRIBER_EXTERNAL_ID")
    Flatten.newline("\t\tORDER BY TIMESTAMP DESC")
    Flatten.newline("\t) = 1")
    Flatten.newline("),")

    # MOSTRECENTEMAIL
    Flatten.newline("MOSTRECENTEMAIL AS (")
    Flatten.newline("\tSELECT")
    Flatten.newlinelist(str_list=ctebaseselectformatted, padding="\t\t")
    Flatten.newline("\t\t,SUBSCRIBER_EMAIL")
    Flatten.newline("\tFROM FLATTENJSON")
    Flatten.newline("\tWHERE LEN(SUBSCRIBER_EMAIL) > 1")
    Flatten.newline("\tQUALIFY ROW_NUMBER() OVER (")
    Flatten.newline("\t\tPARTITION BY SUBSCRIBER_EXTERNAL_ID")
    Flatten.newline("\t\tORDER BY TIMESTAMP DESC")
    Flatten.newline("\t) = 1")
    Flatten.newline("),")

    # MOSTRECENT
    Flatten.newline("MOSTRECENT AS (")
    Flatten.newline("\tSELECT")
    Flatten.newlinelist(str_list=finalselectformatted, padding="\t\t")
    Flatten.newline("\tFROM MOSTRECENTNAME NM")
    Flatten.newline("\tLEFT JOIN MOSTRECENTPHONE PH")
    Flatten.newline("\tON NM.SUBSCRIBER_EXTERNAL_ID = PH.SUBSCRIBER_EXTERNAL_ID")
    Flatten.newline("\tLEFT JOIN MOSTRECENTEMAIL EM")
    Flatten.newline("\tON NM.SUBSCRIBER_EXTERNAL_ID = EM.SUBSCRIBER_EXTERNAL_ID")
    Flatten.newline("),")

    # PIVOTRESULT
    Flatten.newline("PIVOTRESULT AS (")
    Flatten.newline("SELECT")
    Flatten.newlinelist(pivotresultselect)
    Flatten.newline("FROM MOSTRECENT")
    Flatten.newline("\tPIVOT (")
    Flatten.newline("\t\tMAX(USER_PROPERTY_VALUE) FOR USER_PROPERTY_NAME IN (")
    Flatten.newline("\t\t\t'FIRSTNAME',")
    Flatten.newline("\t\t\t'LASTNAME'")
    Flatten.newline("\t\t)")
    Flatten.newline("\t)")
    Flatten.newline("\tAS MOSTRECENT_PIVOT (")
    Flatten.newlinelist(str_list=pivotresultselect, padding="\t")
    Flatten.newline("\t)")
    Flatten.newline("),")

    # PERSONS
    Flatten.newline("PERSONS AS (")
    Flatten.newline("SELECT")
    Flatten.newline("\tMAX(FL.FILEDATE) AS FILEDATE,")
    Flatten.newline("\tMAX(FL.FILENAME) AS FILENAME,")
    Flatten.newline("\tNULL AS FILEROWNUMBER,")
    Flatten.newlinelist(pivotselect)
    Flatten.newline("FROM PIVOTRESULT PR")
    Flatten.newline("LEFT JOIN FLATTENJSON FL")
    Flatten.newline("ON PR.SUBSCRIBER_EXTERNAL_ID = FL.SUBSCRIBER_EXTERNAL_ID")
    Flatten.newline("GROUP BY ALL")
    Flatten.newline(")")

    # Final Select
    Flatten.newline("SELECT")
    Flatten.newline("\tS.FILEDATE,")
    Flatten.newline("\tS.FILENAME,")
    Flatten.newline("\tS.FILEROWNUMBER,")
    Flatten.newline("\tS.TIMESTAMP,")
    Flatten.newline("\tS.COMPANYDISPLAYNAME AS COMPANY_DISPLAY_NAME,")
    Flatten.newline("\tS.COMPANYCOMPANYID AS COMPANY_COMPANY_ID,")
    Flatten.newline("\tS.SUBSCRIBEREXTERNALID AS SUBSCRIBER_EXTERNAL_ID,")
    Flatten.newline("\tS.SUBSCRIBERPHONEFORMATTED AS SUBSCRIBER_PHONE,")
    Flatten.newline("\tS.SUBSCRIBEREMAIL AS SUBSCRIBER_EMAIL,")
    Flatten.newline("\tP.FIRSTNAME,")
    Flatten.newline("\tP.LASTNAME")
    Flatten.newline("FROM STAGE.ATTENTIVESMSSUBSCRIBED S")
    Flatten.newline("LEFT JOIN PERSONS P")
    Flatten.newline("ON S.SUBSCRIBERPHONEFORMATTED=P.SUBSCRIBER_PHONE")
    Flatten.newline(";")

    # define output folder and filename
    filename = f"{table_name.lower()}-flatten.sql"
    output_folder = f"{db_folder}config_repo{os.sep}sources{os.sep}"

    # write output repo files if repo_root_folder is not empty
    if repo_root_folder != "":
        configrepo_folder = f"{repo_root_folder}kagr-configuration{os.sep}prefect{os.sep}{client.upper()}{os.sep}{source_name.lower()}{os.sep}sources{os.sep}"

    # write flatten insert to file
    filewrite(folder=output_folder, filename=filename, content=Flatten.out())

    # write output repo files if repo_root_folder is not empty
    if repo_root_folder != "":
        filewrite(folder=configrepo_folder, filename=filename, content=Flatten.out())

    # trace log
    print_section_detail(msg=f"FLATTEN - {filename}\nCreated in: {output_folder}", runlog=runlog)

    return filename

# # ----------------------------------------------------------------
# # Create unique tmp table SP
# # ----------------------------------------------------------------
# def fn_create_unique_sp_custom(table_name:str, pk_list:list, col_list:list, db_folder:str, runlog:object, std_ind:str, repo_root_folder:str, client:str, source_name:str, import_view_name:str="", create_keyhash:str="0"):
#     runlog.log("Running Attentive Create Unique SP")
#     table_name = table_name.upper()
#
#     unique_sp_name = create_unique_sp(table_name=table_name, pk_list=pk_list, col_list=col_list, db_folder=db_folder, runlog=runlog, std_ind=std_ind, repo_root_folder=repo_root_folder, client=client, source_name="attentive", import_view_name=import_view_name, pk_case_sensitive=True)
#
#     return unique_sp_name

# # ----------------------------------------------------------------
# # Create merge SP
# # ----------------------------------------------------------------
# def fn_create_merge_sp_custom(table_name:str, pk_list:list, col_list:list, db_folder:str, runlog:object, std_ind:str, repo_root_folder:str, client:str, source_name:str, create_keyhash:str="0"):
#     runlog.log("Running Attentive Create Merge SP")
#
#     merge_sp_name = create_merge_sp(table_name=table_name, pk_list=pk_list, col_list=col_list, db_folder=db_folder, runlog=runlog, std_ind=std_ind, repo_root_folder=repo_root_folder, client=client, source_name="attentive", pk_case_sensitive=True)
#
#     return merge_sp_name