from Library.FunctionFiles.Functions import *
from importlib import import_module

installDocAdditions = ["-fr formstack -s kagr -c sp_retrieveformids"]

# ----------------------------------------------------------------
# Create CopyInto File (deprecated)
# ----------------------------------------------------------------
# def fn_create_copyinto_custom(client:str, source_name:str, table_name:str, col_list:list, file_match_text:str, file_date_regex:str, field_delimiter:str, version:str, db_folder:str, runlog:object, field_enclosed_by:str, custom_fileformat_options:str, repo_root_folder:str, worksheet:object):
#     if table_name.upper() != "FORMSTACKSUBMISSIONS":
#         runlog.log("Running Formstack specific copyinto function")
#
#         # initialize CopyInto Document
#         CopyInto = Document()
#
#         # build column list
#         copyintocolumns = []
#         copyelements = []
#         for col in col_list:
#             copyintocolumns.append(f"\t{col[1].upper()}")
#             if col[1].upper() != "BLOB":
#                 copyelements.append(f"\t\tjson_extract_path_text(T.\"$1\"::VARIANT, '{col[0]}') AS {col[1]}")
#
#         # format custom_fileformat_options
#         custom_fileformat_options = custom_fileformat_options.strip()
#
#         if custom_fileformat_options == "None":
#             custom_fileformat_options = ""
#         elif custom_fileformat_options != '':
#             custom_fileformat_options = f" {custom_fileformat_options}"
#         else:
#             custom_fileformat_options = ""
#
#         # define stage location path
#         stage_location = f"@&database.IMPORT.IMPORTSTAGING/{source_name.capitalize()}/&database"
#
#         # build CopyInto statement
#         CopyInto.append(f"/*{table_name} Copy Into version={version} generated by config generator */")
#         CopyInto.newline(f"COPY INTO &database.IMPORT.{table_name.upper()}")
#         CopyInto.newline("(")
#         CopyInto.newline("\tFILEDATE,")
#         CopyInto.newline("\tFILENAME,")
#         CopyInto.newline("\tFILEROWNUMBER,")
#         CopyInto.newlinelist(copyintocolumns)
#         CopyInto.newline(")")
#         CopyInto.newline("FROM")
#         CopyInto.newline("(")
#         CopyInto.newline("\tSELECT")
#         CopyInto.newline(f"\t\tTO_DATE(REGEXP_SUBSTR(METADATA$FILENAME, '{file_date_regex}', 1, 1), 'YYYYMMDD'),")
#         CopyInto.newline("\t\tMETADATA$FILENAME,")
#         CopyInto.newline("\t\tMETADATA$FILE_ROW_NUMBER,")
#         CopyInto.newline("\t\tT.\"$1\",")
#         CopyInto.newlinelist(copyelements)
#         CopyInto.newline("\tFROM ")
#         CopyInto.append(f"{stage_location} T")
#         CopyInto.newline(")")
#         CopyInto.newline(f"PATTERN = '{client.upper()}/{source_name.capitalize()}/&database/{table_name}/{file_match_text}'")
#         CopyInto.newline("ON_ERROR = CONTINUE")
#         CopyInto.newline(f"FILE_FORMAT = (TYPE = JSON STRIP_OUTER_ARRAY = TRUE{custom_fileformat_options})")
#         CopyInto.newline(";")
#
#         # define output folder and filename
#         filename = f"{table_name.lower()}-copy.sql"
#         output_folder = f"{db_folder}sources{os.sep}"
#
#         # write output repo files if repo_root_folder is not empty
#         if repo_root_folder != "":
#             configrepo_folder = f"{repo_root_folder}kagr-configuration{os.sep}prefect{os.sep}{client.upper()}{os.sep}{source_name.lower()}{os.sep}sources{os.sep}"
#
#
#         # write copyinto to file
#         filewrite(folder=output_folder, filename=filename, content=CopyInto.out())
#         print_section_detail(msg=f"COPYINTO - {filename}\nCreated in: {output_folder}", runlog=runlog)
#
#         # write output repo files if repo_root_folder is not empty
#         if repo_root_folder != "":
#             filewrite(folder=configrepo_folder, filename=filename, content=CopyInto.out())
#             print_section_detail(msg=f"COPYINTO - {filename}\nCreated in: {configrepo_folder}", runlog=runlog)
#
#         runlog.log("")
#         return filename
#
#     else:
#         return None

# ----------------------------------------------------------------
# Append File Transfers
# ----------------------------------------------------------------
def fn_file_transfers_append(file_transfers_obj:object, client_project:str, runlog:object):
    runlog.log("Running Formstack specific file_transfers append function")

    file_transfers_obj.append("MASTERSCHEDULE", f"../{client_project}/Formstack_Master")

    runlog.log("")
    return

# ----------------------------------------------------------------
# Append Business Rules
# ----------------------------------------------------------------
def fn_busrules_append(worksheet:object, bus_rule_obj:object, db_folder:str, runlog:object):
    runlog.log("Running Formstack specific busrules append function")

    table_name = worksheet.table_name()

    # ----------------------------------------------------------------
    # FormstackSubmissions
    # ----------------------------------------------------------------
    if table_name.upper() == "FORMSTACKSUBMISSIONS":
        runlog.log("Generate FormstackSubmissions Business Rules.")

        # get client name
        client = db_folder.split(os.sep)
        client.reverse()
        client = client[2].upper()

        # import client specific submissions_2_0 rule
        try:
            # load client specific submissions_bus_rule file
            submissions_busrule_plugin_name = f"SourcePlugins.Formstack.Functions_Formstack_Submissions_Busrule_2_0_{client}"
            submissions_busrule_plugin = import_module(submissions_busrule_plugin_name)
            fn_submissions_bus_rule_2_0 = getattr(submissions_busrule_plugin, "fn_submissions_bus_rule_2_0")
            runlog.log(f"{indent}Using {submissions_busrule_plugin_name} to generate Submissions bus rule 2_0.")
        except:
            runlog.log(
                f"{indent}{submissions_busrule_plugin_name} not found. Using standard bus rule to generate Submissions bus rule 2_0.")
            runlog.log("")
            # load basic flatten
            try:
                submissions_busrule_plugin = import_module("SourcePlugins.Formstack.Functions_Formstack_Submissions_Busrule_2_0_STD")
                fn_submissions_bus_rule_2_0 = getattr(submissions_busrule_plugin, "fn_submissions_bus_rule_2_0")
            except:
                runlog.log(
                    f"{indent}ERROR: Functions_Formstack_Submissions_Busrule_2_0_Std not found. Terminating processing.")
                raise Exception

        # import client specific submissions_3_0 rule
        try:
            # load client specific submissions_bus_rule file
            submissions_busrule_plugin_name = f"SourcePlugins.Formstack.Functions_Formstack_Submissions_Busrule_3_0_{client}"
            submissions_busrule_plugin = import_module(submissions_busrule_plugin_name)
            fn_submissions_bus_rule_3_0 = getattr(submissions_busrule_plugin, "fn_submissions_bus_rule_3_0")
            runlog.log(f"{indent}Using {submissions_busrule_plugin_name} to generate Submissions bus rule 3_0.")
        except:
            runlog.log(
                f"{indent}{submissions_busrule_plugin_name} not found. Using standard bus rule to generate Submissions bus rule 3_0.")
            runlog.log("")
            # load basic flatten
            try:
                submissions_busrule_plugin = import_module("SourcePlugins.Formstack.Functions_Formstack_Submissions_Busrule_3_0_STD")
                fn_submissions_bus_rule_3_0 = getattr(submissions_busrule_plugin, "fn_submissions_bus_rule_3_0")
            except:
                runlog.log(
                    f"{indent}ERROR: Functions_Formstack_Submissions_Busrule_3_0_Std not found. Terminating processing.")
                raise Exception

        # define variables
        output_folder = f"{db_folder}ForReferenceOnly{os.sep}FormstackSubmissions_BusRules{os.sep}"
        col_list = worksheet.columns()
        pk_list = worksheet.primary_keys()

        # get master form id
        master_form_id = str(worksheet.tableinfo()["MasterFormID"]).strip()

        # # get column that is Variant data type
        # variant_col = str(worksheet.tableinfo()["VariantColumnName"]).strip()

        # get FieldID column
        FieldID_col = str(worksheet.tableinfo()["FieldIDColumnName"]).strip()

        # get FieldName column
        FieldName_col = str(worksheet.tableinfo()["FieldNameColumnName"]).strip()

        # get FieldLabel column
        FieldLabel_col = str(worksheet.tableinfo()["FieldLabelColumnName"]).strip()

        # get FieldID column
        FormID_col = str(worksheet.tableinfo()["FormIDColumnName"]).strip()

        # get FormName column
        FormName_col = str(worksheet.tableinfo()["FormNameColumnName"]).strip()

        # ----------------------------------------------------------------
        # Rule 1_0
        # ----------------------------------------------------------------
        busrule = {}
        busrule["ruleName"] = "FormstackSubmissions_1_0"
        busrule["runOrder"] = 1
        busrule["runPosition"] = 0

        ruleQuerydoc = Document()
        ruleQuerydoc.append("TRUNCATE TABLE &database.IMPORT.FORMSTACKSUBMISSIONS;")

        # write out Rule Query to file
        filewrite(folder=output_folder, filename="FormstackSubmissions_1_0 TRUNCATE IMPORT FORMSTACKSUBMISSIONS RULE QUERY.sql", content=ruleQuerydoc.out())

        busrule["ruleQuery"] = ruleQuerydoc.out_str()

        bus_rule_obj.add_rule(busrule)

        # ----------------------------------------------------------------
        # Rule 2_0
        # ----------------------------------------------------------------
        busrule = {}
        busrule["ruleName"] = "FormstackSubmissions_2_0"
        busrule["runOrder"] = 2
        busrule["runPosition"] = 0

        # splitting out this into its own function in case client specific versions need to be created
        ruleQuerydoc = fn_submissions_bus_rule_2_0(col_list = col_list, pk_list = pk_list, field_id_col = FieldID_col, field_name_col = FieldName_col, field_label_col = FieldLabel_col, form_name_col = FormName_col, form_id_col = FormID_col, master_form_id = master_form_id)

        # write out Rule Query to file
        filewrite(folder=output_folder, filename="FormstackSubmissions_2_0 INSERT IMPORT FORMSTACKSUBMISSIONS RULE QUERY.sql", content=ruleQuerydoc.out())

        busrule["ruleQuery"] = ruleQuerydoc.out_str()

        bus_rule_obj.add_rule(busrule)

        # ----------------------------------------------------------------
        # Rule 3_0
        # ----------------------------------------------------------------
        busrule = {}
        busrule["ruleName"] = "FormstackSubmissions_3_0"
        busrule["runOrder"] = 3
        busrule["runPosition"] = 0

        # splitting out this into its own function in case client specific versions need to be created
        ruleQuerydoc = fn_submissions_bus_rule_3_0(col_list = col_list, field_id_col = FieldID_col, field_name_col = FieldName_col, field_label_col = FieldLabel_col, form_name_col = FormName_col, form_id_col = FormID_col, master_form_id = master_form_id)

        # write out Rule Query to file
        filewrite(folder=output_folder, filename="FormstackSubmissions_3_0 INSERT IMPORT FORMSTACKSUBMISSIONS RULE QUERY.sql", content=ruleQuerydoc.out())

        busrule["ruleQuery"] = ruleQuerydoc.out_str()

        bus_rule_obj.add_rule(busrule)

    return

# ----------------------------------------------------------------
# Sources Append
# ----------------------------------------------------------------
def fn_sources_append(worksheet:object, db_folder:str, sources_obj:object, runlog:object, repo_root_folder:str, client:str, source_name:str):
    runlog.log("Running Formstack specific sources append function")

    # get table name
    table_name = worksheet.table_name().lower()

    sources_obj.append("rowCountCheckOverride", 1)

    if table_name.upper() == "FORMSTACKSUBMISSIONS":
        sources_obj.append("dlpColumns", "MISCDATA")
    elif table_name.upper() == "FORMSTACKFORMDETAILSBLOB" or table_name.upper() == "FORMSTACKSUBMISSIONSBLOB":
        # get column that is Variant data type
        variant_col = clookup(worksheet=worksheet.worksheet, lookup_col="DataType", lookup_val="VARIANT", return_col="ColumnName")

        sources_obj.append("dlpColumns", variant_col[0])

    return

# ----------------------------------------------------------------
# Flatten
# ----------------------------------------------------------------
def fn_create_flatten_custom(source_name:str, table_name:str, table_name_raw:str, col_list:list, version:str, db_folder:str, runlog:object, repo_root_folder:str, client:str, worksheet: object):
    runlog.log("Running Formstack specific flatten function")

    # col_list_custom = customize_col_list(table_name, col_list)
    col_list_custom = col_list

    # create flatten if table is not formstack submissions. Submissions gets populated by business rules.
    flatten_filename = ""
    if 'FORMSTACKSUBMISSIONS' not in table_name.upper():
        flatten_filename = create_flatten(source_name=source_name, table_name=table_name.lower(), table_name_raw=table_name_raw, col_list=col_list_custom, version=version, db_folder=db_folder, runlog=runlog, repo_root_folder=repo_root_folder, client=client)

    return flatten_filename
