import copy

std_cols = [
    # ["EMAIL", "RAWEMAIL"],
    # ["", "RAWPREFIX"],
    # ["FIRSTNAME", "RAWFIRSTNAME"],
    # ["", "RAWMIDDLENAME"],
    # ["LASTNAME", "RAWLASTNAME"],
    # ["", "RAWSUFFIX"],
    # ["NAME", "RAWFULLNAME"],
    # ["MAILINGSTREET","RAWADDRESS1"],
    # ["","RAWADDRESS2"],
    # ["","RAWADDRESS3"],
    # ["MAILINGCITY","RAWCITY"],
    # ["MAILINGSTATE","RAWSTATE"],
    # ["MAILINGPOSTALCODE","RAWZIP"],
    # ["MAILINGCOUNTRY","RAWCOUNTRY"],
    # ["PHONE","RAWPHONE"],
    # ["","RAWCOMPANY"],
    ["","ADDRESSDELIVERYINSTALLATION"],
    ["", "ADDRESSEXTRAS"],
    ["", "ADDRESSHOUSENUMBER"],
    ["", "ADDRESSKEY"],
    ["MAILINGSTREET","ADDRESS1"],
    ["", "ADDRESS2"],
    ["", "ADDRESS3"],
    ["", "ADDRESSLOCKBOX"],
    ["", "ADDRESSPOSTDIRECTION"],
    ["", "ADDRESSPREDIRECTION"],
    ["", "ADDRESSPRIVATEMAILBOXNAME"],
    ["", "ADDRESSPRIVATEMAILBOXRANGE"],
    ["", "ADDRESSROUTESERVICE"],
    ["", "ADDRESSSTREETNAME"],
    ["", "ADDRESSSTREETSUFFIX"],
    ["", "ADDRESSSUITENAME"],
    ["", "ADDRESSSUITENUMBER"],
    ["", "ADDRESSTYPECODE"],
    ["", "AREACODE"],
    ["", "CBSACODE"],
    ["", "CBSADIVISIONCODE"],
    ["", "CBSADIVISIONLEVEL"],
    ["", "CBSADIVISIONTITLE"],
    ["", "CBSALEVEL"],
    ["", "CBSATITLE"],
    ["", "CARRIERROUTE"],
    ["", "CENSUSBLOCK"],
    ["", "CENSUSKEY"],
    ["", "CENSUSTRACT"],
    ["MAILINGCITY","CITY"],
    ["", "CITYABBREVIATION"],
    ["", "COMPANYNAME"],
    ["", "CONGRESSIONALDISTRICT"],
    ["", "COUNTRYCODE"],
    ["MAILINGCOUNTRY","COUNTRYNAME"],
    ["", "COUNTYFIPS"],
    ["", "COUNTYNAME"],
    ["", "COUNTYSUBDIVISIONCODE"],
    ["", "COUNTYSUBDIVISIONNAME"],
    ["", "DATEOFBIRTH"],
    ["", "DATEOFDEATH"],
    ["", "DELIVERYINDICATOR"],
    ["", "DELIVERYPOINTCHECKDIGIT"],
    ["", "DELIVERYPOINTCODE"],
    ["", "DEMOGRAPHICSGENDER"],
    ["", "DEMOGRAPHICSRESULTS"],
    ["DISTANCETOVENUE","DISTANCETOVENUE"],
    ["", "DOMAINNAME"],
    ["", "ELEMENTARYSCHOOLDISTRICTCODE"],
    ["", "ELEMENTARYSCHOOLDISTRICTNAME"],
    ["EMAIL","EMAIL"],
    ["", "GENDER"],
    ["", "GENDER2"],
    ["", "HOUSEHOLDINCOME"],
    ["LATITUDE","LATITUDE"],
    ["", "LENGTHOFRESIDENCE"],
    ["LONGITUDE","LONGITUDE"],
    ["", "MAILBOXNAME"],
    ["", "MARITALSTATUS"],
    ["", "MELISSAADDRESSKEY"],
    ["", "METROAREA"],
    ["FIRSTNAME","NAMEFIRST"],
    ["", "NAMEFIRST2"],
    ["NAME", "NAMEFULL"],
    ["LASTNAME", "NAMELAST"],
    ["", "NAMELAST2"],
    ["", "NAMEMIDDLE"],
    ["", "NAMEMIDDLE2"],
    ["", "NAMEPREFIX"],
    ["", "NAMEPREFIX2"],
    ["", "NAMESUFFIX"],
    ["", "NAMESUFFIX2"],
    ["", "NEWAREACODE"],
    ["", "PHONEEXTENSION"],
    ["PHONE", "PHONENUMBER"],
    ["", "PHONEPREFIX"],
    ["", "PHONESUFFIX"],
    ["", "PLACECODE"],
    ["", "PLACENAME"],
    ["", "PRESENCEOFCHILDREN"],
    ["", "RECORDEXTRAS"],
    ["", "RESERVED"],
    ["", "RESULTS"],
    ["", "SALUTATION"],
    ["", "SECONDARYSCHOOLDISTRICTCODE"],
    ["", "SECONDARYSCHOOLDISTRICTNAME"],
    ["MAILINGSTATE", "STATE"],
    ["", "STATEDISTRICTLOWER"],
    ["", "STATEDISTRICTUPPER"],
    ["MAILINGSTATE", "STATENAME"],
    ["", "TOPLEVELDOMAIN"],
    ["", "UTC"],
    ["", "UNIFIEDSCHOOLDISTRICTCODE"],
    ["", "UNIFIEDSCHOOLDISTRICTNAME"],
    ["", "URBANIZATIONNAME"],
    ["MAILINGPOSTALCODE","ZIP"],
    ["", "NCOAADDRESS1"],
    ["", "NCOAADDRESS2"],
    ["", "NCOACITY"],
    ["", "NCOASTATE"],
    ["", "NCOAZIP"],
    ["", "NCOACOUNTRY"],
    ["", "NCOADISTANCETOVENUE"],
    ["", "NCOAPROCESSDATE"],
    ["", "NCOASTATUS"],
    ["", "NCOAMOVEDATE"],
    ["", "ROUTE"],
    ["", "STANDARDIZATIONDATE"],
    ["", "DWINSERTDATE"],
    ["", "DWUPDATEDATE"]
]

std_cols_raw = copy.deepcopy(std_cols)
std_cols_raw.append(["EMAIL", "RAWEMAIL"])
std_cols_raw.append(["", "RAWPREFIX"])
std_cols_raw.append(["FIRSTNAME", "RAWFIRSTNAME"])
std_cols_raw.append(["", "RAWMIDDLENAME"])
std_cols_raw.append(["LASTNAME", "RAWLASTNAME"])
std_cols_raw.append(["", "RAWSUFFIX"])
std_cols_raw.append(["NAME", "RAWFULLNAME"])
std_cols_raw.append(["MAILINGSTREET","RAWADDRESS1"])
std_cols_raw.append(["","RAWADDRESS2"])
std_cols_raw.append(["","RAWADDRESS3"])
std_cols_raw.append(["MAILINGCITY","RAWCITY"])
std_cols_raw.append(["MAILINGSTATE","RAWSTATE"])
std_cols_raw.append(["MAILINGPOSTALCODE","RAWZIP"])
std_cols_raw.append(["MAILINGCOUNTRY","RAWCOUNTRY"])
std_cols_raw.append(["PHONE","RAWPHONE"])
std_cols_raw.append(["","RAWCOMPANY"])

std_pk_cols = ["RAWEMAIL", "RAWPREFIX", "RAWFIRSTNAME", "RAWMIDDLENAME", "RAWLASTNAME", "RAWSUFFIX", "RAWFULLNAME", "RAWADDRESS1", "RAWADDRESS2", "RAWADDRESS3", "RAWCITY", "RAWSTATE", "RAWZIP", "RAWCOUNTRY", "RAWPHONE", "RAWCOMPANY"]