import copy

std_cols = [
    # ["emailaddress1", "RAWEMAIL"],
    # ["", "RAWPREFIX"],
    # ["firstname", "RAWFIRSTNAME"],
    # ["middlename", "RAWMIDDLENAME"],
    # ["lastname", "RAWLASTNAME"],
    # ["", "RAWSUFFIX"],
    # ["fullname", "RAWFULLNAME"],
    # ["address1_line1","RAWADDRESS1"],
    # ["address1_line2","RAWADDRESS2"],
    # ["address1_line3","RAWADDRESS3"],
    # ["address1_city","RAWCITY"],
    # ["address1_stateorprovince","RAWSTATE"],
    # ["address1_postalcode","RAWZIP"],
    # ["address1_country","RAWCOUNTRY"],
    # ["telephone1","RAWPHONE"],
    # ["name","RAWCOMPANY"],
    ["","ADDRESSDELIVERYINSTALLATION"],
    ["", "ADDRESSEXTRAS"],
    ["", "ADDRESSHOUSENUMBER"],
    ["", "ADDRESSKEY"],
    ["address1_line1","ADDRESS1"],
    ["address1_line2", "ADDRESS2"],
    ["address1_line3", "ADDRESS3"],
    ["", "ADDRESSLOCKBOX"],
    ["", "ADDRESSPOSTDIRECTION"],
    ["", "ADDRESSPREDIRECTION"],
    ["", "ADDRESSPRIVATEMAILBOXNAME"],
    ["", "ADDRESSPRIVATEMAILBOXRANGE"],
    ["", "ADDRESSROUTESERVICE"],
    ["", "ADDRESSSTREETNAME"],
    ["", "ADDRESSSTREETSUFFIX"],
    ["", "ADDRESSSUITENAME"],
    ["", "ADDRESSSUITENUMBER"],
    ["", "ADDRESSTYPECODE"],
    ["", "AREACODE"],
    ["", "CBSACODE"],
    ["", "CBSADIVISIONCODE"],
    ["", "CBSADIVISIONLEVEL"],
    ["", "CBSADIVISIONTITLE"],
    ["", "CBSALEVEL"],
    ["", "CBSATITLE"],
    ["", "CARRIERROUTE"],
    ["", "CENSUSBLOCK"],
    ["", "CENSUSKEY"],
    ["", "CENSUSTRACT"],
    ["address1_city","CITY"],
    ["", "CITYABBREVIATION"],
    ["name", "COMPANYNAME"],
    ["", "CONGRESSIONALDISTRICT"],
    ["", "COUNTRYCODE"],
    ["address1_country","COUNTRYNAME"],
    ["", "COUNTYFIPS"],
    ["", "COUNTYNAME"],
    ["", "COUNTYSUBDIVISIONCODE"],
    ["", "COUNTYSUBDIVISIONNAME"],
    ["", "DATEOFBIRTH"],
    ["", "DATEOFDEATH"],
    ["", "DELIVERYINDICATOR"],
    ["", "DELIVERYPOINTCHECKDIGIT"],
    ["", "DELIVERYPOINTCODE"],
    ["", "DEMOGRAPHICSGENDER"],
    ["", "DEMOGRAPHICSRESULTS"],
    ["distancetovenue","DISTANCETOVENUE"],
    ["", "DOMAINNAME"],
    ["", "ELEMENTARYSCHOOLDISTRICTCODE"],
    ["", "ELEMENTARYSCHOOLDISTRICTNAME"],
    ["emailaddress1","EMAIL"],
    ["", "GENDER"],
    ["", "GENDER2"],
    ["", "HOUSEHOLDINCOME"],
    ["latitude","LATITUDE"],
    ["", "LENGTHOFRESIDENCE"],
    ["longitude","LONGITUDE"],
    ["", "MAILBOXNAME"],
    ["", "MARITALSTATUS"],
    ["", "MELISSAADDRESSKEY"],
    ["", "METROAREA"],
    ["firstname","NAMEFIRST"],
    ["", "NAMEFIRST2"],
    ["fullname", "NAMEFULL"],
    ["lastname", "NAMELAST"],
    ["", "NAMELAST2"],
    ["middlename", "NAMEMIDDLE"],
    ["", "NAMEMIDDLE2"],
    ["", "NAMEPREFIX"],
    ["", "NAMEPREFIX2"],
    ["", "NAMESUFFIX"],
    ["", "NAMESUFFIX2"],
    ["", "NEWAREACODE"],
    ["", "PHONEEXTENSION"],
    ["telephone1", "PHONENUMBER"],
    ["", "PHONEPREFIX"],
    ["", "PHONESUFFIX"],
    ["", "PLACECODE"],
    ["", "PLACENAME"],
    ["", "PRESENCEOFCHILDREN"],
    ["", "RECORDEXTRAS"],
    ["", "RESERVED"],
    ["", "RESULTS"],
    ["", "SALUTATION"],
    ["", "SECONDARYSCHOOLDISTRICTCODE"],
    ["", "SECONDARYSCHOOLDISTRICTNAME"],
    ["address1_stateorprovince", "STATE"],
    ["", "STATEDISTRICTLOWER"],
    ["", "STATEDISTRICTUPPER"],
    ["address1_stateorprovince", "STATENAME"],
    ["", "TOPLEVELDOMAIN"],
    ["", "UTC"],
    ["", "UNIFIEDSCHOOLDISTRICTCODE"],
    ["", "UNIFIEDSCHOOLDISTRICTNAME"],
    ["", "URBANIZATIONNAME"],
    ["address1_postalcode","ZIP"],
    ["", "NCOAADDRESS1"],
    ["", "NCOAADDRESS2"],
    ["", "NCOACITY"],
    ["", "NCOASTATE"],
    ["", "NCOAZIP"],
    ["", "NCOACOUNTRY"],
    ["", "NCOADISTANCETOVENUE"],
    ["", "NCOAPROCESSDATE"],
    ["", "NCOASTATUS"],
    ["", "NCOAMOVEDATE"],
    ["", "ROUTE"],
    ["", "STANDARDIZATIONDATE"],
    ["", "DWINSERTDATE"],
    ["", "DWUPDATEDATE"]
]

std_cols_raw = copy.deepcopy(std_cols)
std_cols_raw.append(["emailaddress1", "RAWEMAIL"])
std_cols_raw.append(["", "RAWPREFIX"])
std_cols_raw.append(["firstname", "RAWFIRSTNAME"])
std_cols_raw.append(["middlename", "RAWMIDDLENAME"])
std_cols_raw.append(["lastname", "RAWLASTNAME"])
std_cols_raw.append(["", "RAWSUFFIX"])
std_cols_raw.append(["fullname", "RAWFULLNAME"])
std_cols_raw.append(["address1_line1","RAWADDRESS1"])
std_cols_raw.append(["address1_line2","RAWADDRESS2"])
std_cols_raw.append(["address1_line3","RAWADDRESS3"])
std_cols_raw.append(["address1_city","RAWCITY"])
std_cols_raw.append(["address1_stateorprovince","RAWSTATE"])
std_cols_raw.append(["address1_postalcode","RAWZIP"])
std_cols_raw.append(["address1_country","RAWCOUNTRY"])
std_cols_raw.append(["telephone1","RAWPHONE"])
std_cols_raw.append(["name","RAWCOMPANY"])

std_pk_cols = ["RAWEMAIL", "RAWPREFIX", "RAWFIRSTNAME", "RAWMIDDLENAME", "RAWLASTNAME", "RAWSUFFIX", "RAWFULLNAME", "RAWADDRESS1", "RAWADDRESS2", "RAWADDRESS3", "RAWCITY", "RAWSTATE", "RAWZIP", "RAWCOUNTRY", "RAWPHONE", "RAWCOMPANY"]