from Library.FunctionFiles.Functions import *
from SourcePlugins.Clvmodel.CLVModelBaseColumns import *
import copy

# ----------------------------------------------------------------
# Create CopyInto File
# ----------------------------------------------------------------
def fn_create_copyinto_custom(client:str, source_name:str, table_name:str, col_list:list, file_match_text:str, file_date_regex:str, field_delimiter:str, version:str, db_folder:str, runlog:object, field_enclosed_by:str, custom_fileformat_options:str, repo_root_folder:str, worksheet:object):
    # build column list
    elementidx = 1
    copyintocolumns = []
    copyelements = []
    for col in col_list:
        copyintocolumns.append(f"\t{col[1].upper()}")
        copyelements.append(f"\t\tT.\"${str(elementidx)}\"")
        elementidx += 1

    table_name_folder = ""
    # interpret table to folder
    if "CLVMODELOUTPUTFULL" in table_name.upper():
        table_name_folder = "CLVModelOutputFull"
    elif "CLVFEATUREINSIGHTSFULL" in table_name.upper():
        table_name_folder = "CLVFeatureInsightsFull"
    elif "CLVMODELEXPLAINER" in table_name.upper():
        table_name_folder = "CLVModelExplainerFull"
    else:
        table_name_folder = ""

    # define stage location path
    stage_location = f"@&database.import.ingeststage/CLVModel/&teamAbbr/{table_name_folder}"

    # determine FieldEnclosedBy
    if field_enclosed_by != None:
        copy_field_enclosed_by = f" FIELD_OPTIONALLY_ENCLOSED_BY = '{field_enclosed_by}'"
    else:
        copy_field_enclosed_by = ""

    # format custom_fileformat_options
    custom_fileformat_options = custom_fileformat_options.strip()

    if custom_fileformat_options == "None":
        custom_fileformat_options = ""
    elif custom_fileformat_options != '':
        custom_fileformat_options = f" {custom_fileformat_options}"
    else:
        custom_fileformat_options = ""

    # initialize CopyInto Document
    CopyInto = Document()

    # Write CopyInto statement
    CopyInto.append(f"/*{table_name} Copy Into version={version} generated by config generator */")
    CopyInto.newline(f"COPY INTO &database.IMPORT.{table_name.upper()}")
    CopyInto.newline("(")
    CopyInto.newline("\tFILEDATE,")
    CopyInto.newline("\tFILENAME,")
    CopyInto.newline("\tFILEROWNUMBER,")
    CopyInto.newlinelist(copyintocolumns)
    CopyInto.newline(")")
    CopyInto.newline("FROM")
    CopyInto.newline("(")
    CopyInto.newline("\tSELECT")
    CopyInto.newline(f"\t\tTO_CHAR(REGEXP_SUBSTR(SPLIT_PART(METADATA$FILENAME, '/', -1), '{file_date_regex}', 1, 1)) FILEDATE,")
    CopyInto.newline("\t\tMETADATA$FILENAME,")
    CopyInto.newline("\t\tMETADATA$FILE_ROW_NUMBER,")
    CopyInto.newlinelist(copyelements)
    CopyInto.newline("\tFROM ")
    CopyInto.append(f"{stage_location} T")
    CopyInto.newline(")")
    CopyInto.newline(f"PATTERN = '{file_match_text}'")
    CopyInto.newline("ON_ERROR = CONTINUE")
    CopyInto.newline("FORCE = TRUE")
    CopyInto.newline(
        f"FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = '{field_delimiter}' TRIM_SPACE = TRUE SKIP_HEADER = 1 ENCODING = 'utf-8'{copy_field_enclosed_by}{custom_fileformat_options})")
    CopyInto.newline(";")

    # define output folder and filename

    filename = f"{table_name.lower()}-copy.sql"
    output_folder = f"{db_folder}config_repo{os.sep}sources{os.sep}"

    # write output repo files if repo_root_folder is not empty
    if repo_root_folder != "":
        configrepo_folder = f"{repo_root_folder}kagr-configuration{os.sep}prefect{os.sep}{client.upper()}{os.sep}{source_name.lower()}{os.sep}sources{os.sep}"



    # write copyinto to file
    filewrite(folder=output_folder, filename=filename, content=CopyInto.out())
    print_section_detail(msg=f"COPYINTO - {filename}\nCreated in: {output_folder}", runlog=runlog)

    if repo_root_folder != "":
        filewrite(folder=configrepo_folder, filename=filename, content=CopyInto.out())
        print_section_detail(msg=f"COPYINTO - {filename}\nCreated in: {configrepo_folder}", runlog=runlog)

    return filename

# ----------------------------------------------------------------
# Create stage ddl
# ----------------------------------------------------------------
def fn_create_stage_DDL_custom(table_name:str, col_list:list, pk_str:str, phone_col_list:list, std_ind:int, rawaud_ind:int, version:str, db_folder:str, runlog:object, repo_root_folder:str, client:str, source_name:str, data_resources:list, email_col_list:list=[]):
    # add LATESTMODELRUNFLAG
    col_list_clv = copy.deepcopy(col_list)
    col_list_clv.append(["LATESTMODELRUNFLAG","LATESTMODELRUNFLAG","VARCHAR"])

    StageDDL, StageArchive_DDL = create_stage_DDL(table_name=table_name.lower(), col_list=col_list_clv, pk_str=pk_str, phone_col_list=phone_col_list, std_ind=std_ind, rawaud_ind=rawaud_ind, version=version, db_folder=db_folder, runlog=runlog, repo_root_folder=repo_root_folder, client=client, source_name=source_name, email_col_list=email_col_list)

    # CREATE UPGRADE SCRIPT FROM BASE
    if "CLVMODELOUTPUTFULL" in table_name.upper():
        if len(col_list_clv) - len(clvmodelbasecols)>0:
            runlog.log("Create upgrade script to migrate base clvmodel table to client specific")
            upgradesqlfilename = create_schema_drift_script(table_name=table_name, stage_DDL=StageDDL, old_cols=clvmodelbasecols, db_folder=db_folder, runlog=runlog, repo_root_folder=repo_root_folder, client=client, source_name=source_name, std_ind=std_ind)

    # append data resources
    data_resources.append(["stage", table_name.lower()])

    return StageDDL, data_resources

# ----------------------------------------------------------------
# Create merge SP
# ----------------------------------------------------------------
def fn_create_merge_sp_custom(table_name:str, pk_list:list, col_list:list, db_folder:str, runlog:object, std_ind:str, repo_root_folder:str, client:str, source_name:str, create_keyhash:str="0"):
    # define output folder and filename
    filename = f"sp_mergeinto{table_name.lower()}.sql"
    output_folder = f"{db_folder}data_repo{os.sep}stage{os.sep}"

    runlog.log(f"MERGEINTO - {filename}")

    # set pk_case_sensitive
    pk_case_sensitive = False

    # get data type for pk
    pk_type_list = []
    for col in col_list:
        for pk in pk_list:
            # if pk matches column name, put column list into new list
            if pk == col[1]:
                pk_type_list.append(col)

    # define SP name
    merge_sp_name = f"stage.sp_mergeinto{table_name.lower()}()"
    # initialize merge query document
    mergesp = Document()

    # write query
    mergesp.append(f"/* sp_MergeInto{table_name.upper()} (stage) grantobjectname=stage.sp_MergeInto{table_name.upper()} version=1 */")
    mergesp.newline("!set exit_on_error=true;")
    mergesp.newline("!set variable_substitution=true;")
    mergesp.newline("")
    mergesp.newline(f"CREATE OR REPLACE PROCEDURE {merge_sp_name}")
    mergesp.newline("\treturns varchar not null")
    mergesp.newline("\tlanguage sql")
    mergesp.newline("\texecute as caller")
    mergesp.newline("AS")
    mergesp.newline("$$")
    mergesp.newline("\tBEGIN")

    if std_ind == "1":
        mergesp.newline(
            f"\t\tMERGE INTO STAGE.{table_name.upper()} dest USING TMP.{table_name.upper()}RawAudience sor ON")
    else:
        mergesp.newline(
            f"\t\tMERGE INTO STAGE.{table_name.upper()} dest USING TMP.{table_name.upper()}Unique sor ON")

    if create_keyhash == "1":
        mergesp.newline(f"\t\t\tdest.KEYHASH = sor.KEYHASH")
    else:
        for pk in pk_type_list:
            # if pk is string, lower
            if "VARCHAR" in pk[2].upper() and pk_case_sensitive is False:
                runlog.log("   PK is not case sensitive")
                mergesp.newline(f"\t\t\tlower(dest.{pk[1]}) = lower(sor.{pk[1]}) AND")
            else:
                runlog.log("   PK is case sensitive")
                mergesp.newline(f"\t\t\tdest.{pk[1]} = sor.{pk[1]} AND")

        mergesp.trimend(4)

    mergesp.newline("\t\tWHEN MATCHED AND")
    mergesp.newline("\t\t(")

    if create_keyhash == "1":
        mergesp.newline(f"\t\t\tNOT EQUAL_NULL(dest.KEYHASH, sor.KEYHASH) OR")

    mergesp.newline(f"\t\t\tNOT EQUAL_NULL(dest.FILEDATE, sor.FILEDATE) OR")
    mergesp.newline(f"\t\t\tNOT EQUAL_NULL(dest.FILENAME, sor.FILENAME) OR")
    mergesp.newline(f"\t\t\tNOT EQUAL_NULL(dest.FILEROWNUMBER, sor.FILEROWNUMBER) OR")

    for row in col_list:
        mergesp.newline(f"\t\t\tNOT EQUAL_NULL(dest.{row[1]}, sor.{row[1]}) OR")

    # add standardizationrowid and rawudienceid column if table is customer source
    if std_ind == "1":
        mergesp.newline("\t\t\tNOT EQUAL_NULL(dest.STANDARDIZATIONROWID, sor.STANDARDIZATIONROWID) OR")
        mergesp.newline("\t\t\tNOT EQUAL_NULL(dest.RAWAUDIENCEID, sor.RAWAUDIENCEID)")
    else:
        mergesp.trimend(3)

    mergesp.newline("\t\t)")
    mergesp.newline("\t\tTHEN UPDATE SET")

    mergesp.newline(f"\t\t\tdest.FILEDATE = sor.FILEDATE,")
    mergesp.newline(f"\t\t\tdest.FILENAME = sor.FILENAME,")
    mergesp.newline(f"\t\t\tdest.FILEROWNUMBER = IFNULL(sor.FILEROWNUMBER,0),")

    if create_keyhash == "1":
        mergesp.newline(f"\t\t\tdest.KEYHASH = sor.KEYHASH,")

    for row in col_list:
        mergesp.newline(f"\t\t\tdest.{row[1]} = sor.{row[1]},")

    # add standardizationrowid and rawudienceid column if table is customer source
    if std_ind == "1":
        mergesp.newline("\t\t\tdest.STANDARDIZATIONROWID = sor.STANDARDIZATIONROWID,")
        mergesp.newline("\t\t\tdest.RAWAUDIENCEID = sor.RAWAUDIENCEID,")

    mergesp.newline("\t\t\tdest.DWUPDATEDATE = now(),")
    mergesp.newline("\t\t\tdest.LATESTMODELRUNFLAG = 'YES'")
    mergesp.newline("\t\tWHEN NOT MATCHED THEN INSERT")
    mergesp.newline("\t\t(")

    mergesp.newline(f"\t\t\tFILEDATE,")
    mergesp.newline(f"\t\t\tFILENAME,")
    mergesp.newline(f"\t\t\tFILEROWNUMBER,")

    if create_keyhash == "1":
        mergesp.newline(f"\t\t\tKEYHASH,")
    for row in col_list:
        mergesp.newline(f"\t\t\t{row[1]},")

    # add standardizationrowid and rawudienceid column if table is customer source
    if std_ind == "1":
        mergesp.newline("\t\t\tSTANDARDIZATIONROWID,")
        mergesp.newline("\t\t\tRAWAUDIENCEID,")

    mergesp.newline("\t\t\tDWUPDATEDATE,")
    mergesp.newline("\t\t\tDWINSERTDATE,")
    mergesp.newline("\t\t\tLATESTMODELRUNFLAG")

    mergesp.newline("\t\t) VALUES")
    mergesp.newline("\t\t(")

    mergesp.newline(f"\t\t\tIFNULL(NULLIF(sor.FILEDATE,''),'19000101'),")
    mergesp.newline(f"\t\t\tsor.FILENAME,")
    mergesp.newline(f"\t\t\tIFNULL(sor.FILEROWNUMBER,0),")

    if create_keyhash == "1":
        mergesp.newline(f"\t\t\tsor.KEYHASH,")

    for row in col_list:
        mergesp.newline(f"\t\t\tsor.{row[1]},")

    # add standardizationrowid and rawudienceid column if table is customer source
    if std_ind == "1":
        mergesp.newline("\t\t\tsor.STANDARDIZATIONROWID,")
        mergesp.newline("\t\t\tsor.RAWAUDIENCEID,")

    mergesp.newline("\t\t\tnow(),")
    mergesp.newline("\t\t\tnow(),")
    mergesp.newline("\t\t\t'YES'")
    mergesp.newline("\t\t);")

    mergesp.newline(f"\tRETURN 'FINISHED CALLING STORED PROCEDURE sp_MergeInto{table_name.upper()}';")
    mergesp.newline("\tEND;")
    mergesp.newline("$$;")

    # write output file
    filewrite(folder=output_folder, filename=filename, content=mergesp.out())
    runlog.log(f"   Created in: {output_folder}")

    # write output repo files if repo_root_folder is not empty
    if repo_root_folder != "":
        datarepo_folder = f"{repo_root_folder}data{os.sep}warehouse{os.sep}{source_name.lower()}{os.sep}stage{os.sep}{client.upper()}{os.sep}"
        filewrite(folder=datarepo_folder, filename=filename, content=mergesp.out())
        runlog.log(f"   Created in: {output_folder}")

    return merge_sp_name

# ----------------------------------------------------------------
# Append Business Rules
# ----------------------------------------------------------------
def fn_busrules_append(worksheet:object, bus_rule_obj:object, db_folder:str, runlog:object):
    runlog.log("Running CLVModel specific busrules append function")

    # get table name
    table_name = worksheet.table_name()

    output_folder = f"{db_folder}ForReferenceOnly{os.sep}{table_name}_BusRules{os.sep}"

    # ----------------------------------------------------------------
    # Rule 1_0
    # ----------------------------------------------------------------
    busrule = {}
    busrule["ruleName"] = f"{table_name}_1_0"
    busrule["runOrder"] = 1
    busrule["runPosition"] = 0

    rulequerydoc = Document()
    rulequerydoc.append(f"UPDATE STAGE.{table_name} SET LATESTMODELRUNFLAG = '' WHERE LATESTMODELRUNFLAG = 'YES';")

    # write out Rule Query to file
    filewrite(folder=output_folder, filename=f"{table_name}_1_0 UPDATE LATESTMODELRUNFLAG RULE QUERY.sql", content=rulequerydoc.out())

    busrule["ruleQuery"] = rulequerydoc.out_str()

    bus_rule_obj.add_rule(busrule)

    return